// @ts-nocheck
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Grants Management API
 *
 * Back end API for Grants Management.
 *
 * This API is in early development, and is not yet ready for public use.
 *
 * OpenAPI spec version: v0
 */
import * as zod from 'zod';

export const HealthcheckMetadataSchema = zod.object({
  "commit_sha": zod.string().optional().describe('The github commit sha for the latest deployed commit'),
  "commit_link": zod.string().optional().describe('A github link to the latest deployed commit'),
  "release_notes_link": zod.string().optional().describe('A github link to the release notes - direct if the latest deploy was a release'),
  "last_deploy_time": zod.string().datetime({"offset":true}).optional().describe('Latest deploy time in US\/Eastern timezone'),
  "deploy_whoami": zod.string().optional().describe('The latest user to deploy the application')
});

export type HealthcheckMetadataSchema = zod.input<typeof HealthcheckMetadataSchema>;
export type HealthcheckMetadataSchemaOutput = zod.output<typeof HealthcheckMetadataSchema>;

export const HealthcheckResponseSchema = zod.object({
  "message": zod.string().optional().describe('The message to return'),
  "data": zod.object({
  "commit_sha": zod.string().optional().describe('The github commit sha for the latest deployed commit'),
  "commit_link": zod.string().optional().describe('A github link to the latest deployed commit'),
  "release_notes_link": zod.string().optional().describe('A github link to the release notes - direct if the latest deploy was a release'),
  "last_deploy_time": zod.string().datetime({"offset":true}).optional().describe('Latest deploy time in US\/Eastern timezone'),
  "deploy_whoami": zod.string().optional().describe('The latest user to deploy the application')
}).optional(),
  "status_code": zod.number().int().optional().describe('The HTTP status code')
});

export type HealthcheckResponseSchema = zod.input<typeof HealthcheckResponseSchema>;
export type HealthcheckResponseSchemaOutput = zod.output<typeof HealthcheckResponseSchema>;

export const ValidationIssueSchema = zod.object({
  "type": zod.string().optional().describe('The type of error'),
  "message": zod.string().optional().describe('The message to return'),
  "field": zod.string().optional().describe('The field that failed'),
  "value": zod.string().optional().describe('The value that failed')
});

export type ValidationIssueSchema = zod.input<typeof ValidationIssueSchema>;
export type ValidationIssueSchemaOutput = zod.output<typeof ValidationIssueSchema>;

export const ErrorResponseSchema = zod.object({
  "data": zod.unknown().optional().describe('Additional data that might be useful in resolving an error (see specific endpoints for details, this is used infrequently)'),
  "message": zod.string().optional().describe('General description of the error'),
  "status_code": zod.number().int().optional().describe('The HTTP status code of the error'),
  "errors": zod.array(zod.object({
  "type": zod.string().optional().describe('The type of error'),
  "message": zod.string().optional().describe('The message to return'),
  "field": zod.string().optional().describe('The field that failed'),
  "value": zod.string().optional().describe('The value that failed')
})).optional(),
  "internal_request_id": zod.string().optional().describe('An internal tracking ID')
});

export type ErrorResponseSchema = zod.input<typeof ErrorResponseSchema>;
export type ErrorResponseSchemaOutput = zod.output<typeof ErrorResponseSchema>;

export const LocalUserTokenSchema = zod.object({
  "user_id": zod.string().uuid().optional().describe('The ID of the user'),
  "first_name": zod.string().nullish().describe('The first name of the user'),
  "last_name": zod.string().nullish().describe('The last name of the user'),
  "oauth_id": zod.string().nullish().describe('The OAuth id of the user - can be used to login locally via our mock OAuth server'),
  "user_jwt": zod.string().nullish().describe('The JWT of the user, can be used with our X-MGMT-Token auth'),
  "user_api_key": zod.string().nullish().describe('The API key of the user, can be used with our X-API-Key auth')
});

export type LocalUserTokenSchema = zod.input<typeof LocalUserTokenSchema>;
export type LocalUserTokenSchemaOutput = zod.output<typeof LocalUserTokenSchema>;

export const LocalUserTokenResponseSchema = zod.object({
  "message": zod.string().optional().describe('The message to return'),
  "data": zod.array(zod.object({
  "user_id": zod.string().uuid().optional().describe('The ID of the user'),
  "first_name": zod.string().nullish().describe('The first name of the user'),
  "last_name": zod.string().nullish().describe('The last name of the user'),
  "oauth_id": zod.string().nullish().describe('The OAuth id of the user - can be used to login locally via our mock OAuth server'),
  "user_jwt": zod.string().nullish().describe('The JWT of the user, can be used with our X-MGMT-Token auth'),
  "user_api_key": zod.string().nullish().describe('The API key of the user, can be used with our X-API-Key auth')
})).optional(),
  "status_code": zod.number().int().optional().describe('The HTTP status code')
});

export type LocalUserTokenResponseSchema = zod.input<typeof LocalUserTokenResponseSchema>;
export type LocalUserTokenResponseSchemaOutput = zod.output<typeof LocalUserTokenResponseSchema>;

export const WorkflowEventResponseDataSchema = zod.object({
  "event_id": zod.string().uuid().optional().describe('The tracking ID for the workflow event')
});

export type WorkflowEventResponseDataSchema = zod.input<typeof WorkflowEventResponseDataSchema>;
export type WorkflowEventResponseDataSchemaOutput = zod.output<typeof WorkflowEventResponseDataSchema>;

export const WorkflowEventResponseSchema = zod.object({
  "message": zod.string().optional().describe('The message to return'),
  "data": zod.object({
  "event_id": zod.string().uuid().optional().describe('The tracking ID for the workflow event')
}).optional(),
  "status_code": zod.number().int().optional().describe('The HTTP status code')
});

export type WorkflowEventResponseSchema = zod.input<typeof WorkflowEventResponseSchema>;
export type WorkflowEventResponseSchemaOutput = zod.output<typeof WorkflowEventResponseSchema>;

export const StartWorkflowContextSchema = zod.object({
  "workflow_type": zod.enum(['basic_test_workflow', 'prototype_workflow', 'approval_test_workflow', 'limited_approval_test_workflow']).describe('The type of workflow to initiate'),
  "resource_id": zod.string().uuid().describe('The resource ID of the entity to associate with the workflow - different workflows require different resource types.')
});

export type StartWorkflowContextSchema = zod.input<typeof StartWorkflowContextSchema>;
export type StartWorkflowContextSchemaOutput = zod.output<typeof StartWorkflowContextSchema>;




export const ProcessWorkflowContextSchema = zod.object({
  "workflow_id": zod.string().uuid().describe('The ID of the existing workflow to progress'),
  "event_to_send": zod.string().min(1).describe('The specific event\/action to trigger in the state machine')
});

export type ProcessWorkflowContextSchema = zod.input<typeof ProcessWorkflowContextSchema>;
export type ProcessWorkflowContextSchemaOutput = zod.output<typeof ProcessWorkflowContextSchema>;


export const workflowEventRequestSchemaMetadataDefault = {};

export const WorkflowEventRequestSchema = zod.object({
  "event_type": zod.enum(['start_workflow', 'process_workflow']).describe('The category of event: either starting a new workflow or processing an existing one'),
  "start_workflow_context": zod.object({
  "workflow_type": zod.enum(['basic_test_workflow', 'prototype_workflow', 'approval_test_workflow', 'limited_approval_test_workflow']).describe('The type of workflow to initiate'),
  "resource_id": zod.string().uuid().describe('The resource ID of the entity to associate with the workflow - different workflows require different resource types.')
}).optional().describe('Context and entities required to initialize a new workflow. Only allowed if event_type is \'start_workflow\'.'),
  "process_workflow_context": zod.object({
  "workflow_id": zod.string().uuid().describe('The ID of the existing workflow to progress'),
  "event_to_send": zod.string().min(1).describe('The specific event\/action to trigger in the state machine')
}).optional().describe('Information required to progress an existing workflow state. Only allowed if event_type is \'process_workflow\'.'),
  "metadata": zod.record(zod.string(), zod.unknown()).default(workflowEventRequestSchemaMetadataDefault).describe('A freeform JSON object for the particular event, if needed.')
});

export type WorkflowEventRequestSchema = zod.input<typeof WorkflowEventRequestSchema>;
export type WorkflowEventRequestSchemaOutput = zod.output<typeof WorkflowEventRequestSchema>;

export const UserTokenLogoutResponseSchema = zod.object({
  "message": zod.string().optional().describe('The message to return'),
  "data": zod.unknown().optional(),
  "status_code": zod.number().int().optional().describe('The HTTP status code')
});

export type UserTokenLogoutResponseSchema = zod.input<typeof UserTokenLogoutResponseSchema>;
export type UserTokenLogoutResponseSchemaOutput = zod.output<typeof UserTokenLogoutResponseSchema>;

export const UserTokenRefreshResponseSchema = zod.object({
  "message": zod.string().optional().describe('The message to return'),
  "data": zod.unknown().optional(),
  "status_code": zod.number().int().optional().describe('The HTTP status code')
});

export type UserTokenRefreshResponseSchema = zod.input<typeof UserTokenRefreshResponseSchema>;
export type UserTokenRefreshResponseSchemaOutput = zod.output<typeof UserTokenRefreshResponseSchema>;

export const PartnerSchema = zod.object({
  "partner_id": zod.string().uuid().optional().describe('Unique ID of a partner'),
  "partner_name": zod.string().optional().describe('Name of the partner')
});

export type PartnerSchema = zod.input<typeof PartnerSchema>;
export type PartnerSchemaOutput = zod.output<typeof PartnerSchema>;

export const GetPartnerResponseSchema = zod.object({
  "message": zod.string().optional().describe('The message to return'),
  "data": zod.object({
  "partner_id": zod.string().uuid().optional().describe('Unique ID of a partner'),
  "partner_name": zod.string().optional().describe('Name of the partner')
}).optional(),
  "status_code": zod.number().int().optional().describe('The HTTP status code')
});

export type GetPartnerResponseSchema = zod.input<typeof GetPartnerResponseSchema>;
export type GetPartnerResponseSchemaOutput = zod.output<typeof GetPartnerResponseSchema>;

export const WorkflowUserSchema = zod.object({
  "user_id": zod.string().uuid().optional().describe('The user\'s unique identifier'),
  "email": zod.string().nullish().describe('The user\'s email address, null if they have no login')
});

export type WorkflowUserSchema = zod.input<typeof WorkflowUserSchema>;
export type WorkflowUserSchemaOutput = zod.output<typeof WorkflowUserSchema>;

export const WorkflowApprovalSchema = zod.object({
  "workflow_approval_id": zod.string().uuid().optional().describe('The approval record\'s unique identifier'),
  "approving_user": zod.object({
  "user_id": zod.string().uuid().optional().describe('The user\'s unique identifier'),
  "email": zod.string().nullish().describe('The user\'s email address, null if they have no login')
}).optional().describe('The user who gave this approval'),
  "event_id": zod.string().uuid().optional().describe('The ID of the event that recorded this approval'),
  "is_still_valid": zod.boolean().optional().describe('Whether this approval is still in effect'),
  "comment": zod.string().nullish().describe('An optional comment left with the approval'),
  "approval_type": zod.enum(['basic_test_approval', 'secondary_test_approval']).optional().describe('The type of approval'),
  "approval_response_type": zod.enum(['approved', 'declined', 'requires_modification']).optional().describe('The response given for this approval'),
  "created_at": zod.string().datetime({"offset":true}).optional()
});

export type WorkflowApprovalSchema = zod.input<typeof WorkflowApprovalSchema>;
export type WorkflowApprovalSchemaOutput = zod.output<typeof WorkflowApprovalSchema>;

export const WorkflowApprovalConfigEntrySchema = zod.object({
  "approval_type": zod.enum(['basic_test_approval', 'secondary_test_approval']).optional().describe('The type of approval this event represents'),
  "required_privileges": zod.array(zod.enum(['view_partner', 'update_partner', 'manage_partner_members', 'view_program', 'update_program', 'view_grantor_organization', 'update_grantor_organization', 'manage_grantor_organization_members', 'internal_workflow_event_send', 'unused_privilege_102', 'unused_privilege_103'])).optional().describe('The privileges required to give this approval'),
  "allowed_approval_response_types": zod.array(zod.enum(['approved', 'declined', 'requires_modification'])).optional().describe('The response types this approval accepts'),
  "possible_users": zod.array(zod.object({
  "user_id": zod.string().uuid().optional().describe('The user\'s unique identifier'),
  "email": zod.string().nullish().describe('The user\'s email address, null if they have no login')
})).optional().describe('The users eligible to give this approval')
});

export type WorkflowApprovalConfigEntrySchema = zod.input<typeof WorkflowApprovalConfigEntrySchema>;
export type WorkflowApprovalConfigEntrySchemaOutput = zod.output<typeof WorkflowApprovalConfigEntrySchema>;

export const WorkflowGetResponseDataSchema = zod.object({
  "workflow_id": zod.string().uuid().optional().describe('The workflow\'s unique identifier'),
  "workflow_type": zod.enum(['basic_test_workflow', 'prototype_workflow', 'approval_test_workflow', 'limited_approval_test_workflow']).optional().describe('The type of workflow'),
  "current_workflow_state": zod.string().optional().describe('The workflow\'s current state'),
  "is_active": zod.boolean().optional().describe('Whether the workflow is still active'),
  "resource_id": zod.string().uuid().optional().describe('The resource the workflow is attached to'),
  "resource_type": zod.enum(['internal', 'partner', 'program', 'grantor_organization', 'opportunity']).optional().describe('The type of resource the workflow is attached to'),
  "created_at": zod.string().datetime({"offset":true}).optional(),
  "updated_at": zod.string().datetime({"offset":true}).optional(),
  "workflow_approvals": zod.array(zod.object({
  "workflow_approval_id": zod.string().uuid().optional().describe('The approval record\'s unique identifier'),
  "approving_user": zod.object({
  "user_id": zod.string().uuid().optional().describe('The user\'s unique identifier'),
  "email": zod.string().nullish().describe('The user\'s email address, null if they have no login')
}).optional().describe('The user who gave this approval'),
  "event_id": zod.string().uuid().optional().describe('The ID of the event that recorded this approval'),
  "is_still_valid": zod.boolean().optional().describe('Whether this approval is still in effect'),
  "comment": zod.string().nullish().describe('An optional comment left with the approval'),
  "approval_type": zod.enum(['basic_test_approval', 'secondary_test_approval']).optional().describe('The type of approval'),
  "approval_response_type": zod.enum(['approved', 'declined', 'requires_modification']).optional().describe('The response given for this approval'),
  "created_at": zod.string().datetime({"offset":true}).optional()
})).optional().describe('The approvals recorded against the workflow, sorted oldest to newest'),
  "workflow_approval_config": zod.record(zod.string(), zod.object({
  "approval_type": zod.enum(['basic_test_approval', 'secondary_test_approval']).optional().describe('The type of approval this event represents'),
  "required_privileges": zod.array(zod.enum(['view_partner', 'update_partner', 'manage_partner_members', 'view_program', 'update_program', 'view_grantor_organization', 'update_grantor_organization', 'manage_grantor_organization_members', 'internal_workflow_event_send', 'unused_privilege_102', 'unused_privilege_103'])).optional().describe('The privileges required to give this approval'),
  "allowed_approval_response_types": zod.array(zod.enum(['approved', 'declined', 'requires_modification'])).optional().describe('The response types this approval accepts'),
  "possible_users": zod.array(zod.object({
  "user_id": zod.string().uuid().optional().describe('The user\'s unique identifier'),
  "email": zod.string().nullish().describe('The user\'s email address, null if they have no login')
})).optional().describe('The users eligible to give this approval')
})).optional().describe('For each event that requires an approval, who can give it and how'),
  "valid_events": zod.array(zod.string()).optional().describe('The events that can legally be sent next, given the current state')
});

export type WorkflowGetResponseDataSchema = zod.input<typeof WorkflowGetResponseDataSchema>;
export type WorkflowGetResponseDataSchemaOutput = zod.output<typeof WorkflowGetResponseDataSchema>;

export const WorkflowGetResponseSchema = zod.object({
  "message": zod.string().optional().describe('The message to return'),
  "data": zod.object({
  "workflow_id": zod.string().uuid().optional().describe('The workflow\'s unique identifier'),
  "workflow_type": zod.enum(['basic_test_workflow', 'prototype_workflow', 'approval_test_workflow', 'limited_approval_test_workflow']).optional().describe('The type of workflow'),
  "current_workflow_state": zod.string().optional().describe('The workflow\'s current state'),
  "is_active": zod.boolean().optional().describe('Whether the workflow is still active'),
  "resource_id": zod.string().uuid().optional().describe('The resource the workflow is attached to'),
  "resource_type": zod.enum(['internal', 'partner', 'program', 'grantor_organization', 'opportunity']).optional().describe('The type of resource the workflow is attached to'),
  "created_at": zod.string().datetime({"offset":true}).optional(),
  "updated_at": zod.string().datetime({"offset":true}).optional(),
  "workflow_approvals": zod.array(zod.object({
  "workflow_approval_id": zod.string().uuid().optional().describe('The approval record\'s unique identifier'),
  "approving_user": zod.object({
  "user_id": zod.string().uuid().optional().describe('The user\'s unique identifier'),
  "email": zod.string().nullish().describe('The user\'s email address, null if they have no login')
}).optional().describe('The user who gave this approval'),
  "event_id": zod.string().uuid().optional().describe('The ID of the event that recorded this approval'),
  "is_still_valid": zod.boolean().optional().describe('Whether this approval is still in effect'),
  "comment": zod.string().nullish().describe('An optional comment left with the approval'),
  "approval_type": zod.enum(['basic_test_approval', 'secondary_test_approval']).optional().describe('The type of approval'),
  "approval_response_type": zod.enum(['approved', 'declined', 'requires_modification']).optional().describe('The response given for this approval'),
  "created_at": zod.string().datetime({"offset":true}).optional()
})).optional().describe('The approvals recorded against the workflow, sorted oldest to newest'),
  "workflow_approval_config": zod.record(zod.string(), zod.object({
  "approval_type": zod.enum(['basic_test_approval', 'secondary_test_approval']).optional().describe('The type of approval this event represents'),
  "required_privileges": zod.array(zod.enum(['view_partner', 'update_partner', 'manage_partner_members', 'view_program', 'update_program', 'view_grantor_organization', 'update_grantor_organization', 'manage_grantor_organization_members', 'internal_workflow_event_send', 'unused_privilege_102', 'unused_privilege_103'])).optional().describe('The privileges required to give this approval'),
  "allowed_approval_response_types": zod.array(zod.enum(['approved', 'declined', 'requires_modification'])).optional().describe('The response types this approval accepts'),
  "possible_users": zod.array(zod.object({
  "user_id": zod.string().uuid().optional().describe('The user\'s unique identifier'),
  "email": zod.string().nullish().describe('The user\'s email address, null if they have no login')
})).optional().describe('The users eligible to give this approval')
})).optional().describe('For each event that requires an approval, who can give it and how'),
  "valid_events": zod.array(zod.string()).optional().describe('The events that can legally be sent next, given the current state')
}).optional(),
  "status_code": zod.number().int().optional().describe('The HTTP status code')
});

export type WorkflowGetResponseSchema = zod.input<typeof WorkflowGetResponseSchema>;
export type WorkflowGetResponseSchemaOutput = zod.output<typeof WorkflowGetResponseSchema>;

export const UserCanAccessResponseSchema = zod.object({
  "message": zod.string().optional().describe('The message to return'),
  "data": zod.unknown().optional(),
  "status_code": zod.number().int().optional().describe('The HTTP status code')
});

export type UserCanAccessResponseSchema = zod.input<typeof UserCanAccessResponseSchema>;
export type UserCanAccessResponseSchemaOutput = zod.output<typeof UserCanAccessResponseSchema>;




export const UserCanAccessRequestSchema = zod.object({
  "resource_id": zod.string().uuid().describe('The ID of the resource to check access against'),
  "resource_type": zod.enum(['internal', 'partner', 'program', 'grantor_organization', 'opportunity']).describe('The type of the resource to check access against'),
  "privileges": zod.array(zod.enum(['view_partner', 'update_partner', 'manage_partner_members', 'view_program', 'update_program', 'view_grantor_organization', 'update_grantor_organization', 'manage_grantor_organization_members', 'internal_workflow_event_send', 'unused_privilege_102', 'unused_privilege_103'])).min(1).describe('The privileges the user must have against the resource. The user must have all of them.')
});

export type UserCanAccessRequestSchema = zod.input<typeof UserCanAccessRequestSchema>;
export type UserCanAccessRequestSchemaOutput = zod.output<typeof UserCanAccessRequestSchema>;

export const SortOrderSchema = zod.object({
  "order_by": zod.string().optional().describe('The field that the records were sorted by'),
  "sort_direction": zod.enum(['ascending', 'descending']).optional().describe('The direction the records are sorted')
});

export type SortOrderSchema = zod.input<typeof SortOrderSchema>;
export type SortOrderSchemaOutput = zod.output<typeof SortOrderSchema>;

export const PaginationInfoSchema = zod.object({
  "page_offset": zod.number().int().optional().describe('The page number that was fetched'),
  "page_size": zod.number().int().optional().describe('The size of the page fetched'),
  "total_records": zod.number().int().optional().describe('The total number of records fetchable'),
  "total_pages": zod.number().int().optional().describe('The total number of pages that can be fetched'),
  "sort_order": zod.array(zod.object({
  "order_by": zod.string().optional().describe('The field that the records were sorted by'),
  "sort_direction": zod.enum(['ascending', 'descending']).optional().describe('The direction the records are sorted')
})).optional().describe('The sort order passed in originally')
});

export type PaginationInfoSchema = zod.input<typeof PaginationInfoSchema>;
export type PaginationInfoSchemaOutput = zod.output<typeof PaginationInfoSchema>;

export const WorkflowEventRefSchema = zod.object({
  "event_id": zod.string().uuid().optional().describe('The ID of the event that produced this record'),
  "sent_at": zod.string().datetime({"offset":true}).optional().describe('When the event was sent')
});

export type WorkflowEventRefSchema = zod.input<typeof WorkflowEventRefSchema>;
export type WorkflowEventRefSchemaOutput = zod.output<typeof WorkflowEventRefSchema>;

export const WorkflowAuditEventSchema = zod.object({
  "workflow_audit_id": zod.string().uuid().optional().describe('The audit record\'s unique identifier'),
  "acting_user": zod.object({
  "user_id": zod.string().uuid().optional().describe('The user\'s unique identifier'),
  "email": zod.string().nullish().describe('The user\'s email address, null if they have no login')
}).optional().describe('The user who performed the transition'),
  "transition_event": zod.string().optional().describe('The event that triggered the transition'),
  "source_state": zod.string().optional().describe('The state before the transition'),
  "target_state": zod.string().optional().describe('The state after the transition'),
  "event": zod.object({
  "event_id": zod.string().uuid().optional().describe('The ID of the event that produced this record'),
  "sent_at": zod.string().datetime({"offset":true}).optional().describe('When the event was sent')
}).optional().describe('The event that triggered this transition'),
  "audit_metadata": zod.record(zod.string(), zod.unknown()).nullish().describe('Additional metadata recorded with the transition'),
  "created_at": zod.string().datetime({"offset":true}).optional()
});

export type WorkflowAuditEventSchema = zod.input<typeof WorkflowAuditEventSchema>;
export type WorkflowAuditEventSchemaOutput = zod.output<typeof WorkflowAuditEventSchema>;

export const WorkflowAuditResponseSchema = zod.object({
  "pagination_info": zod.object({
  "page_offset": zod.number().int().optional().describe('The page number that was fetched'),
  "page_size": zod.number().int().optional().describe('The size of the page fetched'),
  "total_records": zod.number().int().optional().describe('The total number of records fetchable'),
  "total_pages": zod.number().int().optional().describe('The total number of pages that can be fetched'),
  "sort_order": zod.array(zod.object({
  "order_by": zod.string().optional().describe('The field that the records were sorted by'),
  "sort_direction": zod.enum(['ascending', 'descending']).optional().describe('The direction the records are sorted')
})).optional().describe('The sort order passed in originally')
}).optional().describe('The pagination information for paginated endpoints'),
  "message": zod.string().optional().describe('The message to return'),
  "data": zod.array(zod.object({
  "workflow_audit_id": zod.string().uuid().optional().describe('The audit record\'s unique identifier'),
  "acting_user": zod.object({
  "user_id": zod.string().uuid().optional().describe('The user\'s unique identifier'),
  "email": zod.string().nullish().describe('The user\'s email address, null if they have no login')
}).optional().describe('The user who performed the transition'),
  "transition_event": zod.string().optional().describe('The event that triggered the transition'),
  "source_state": zod.string().optional().describe('The state before the transition'),
  "target_state": zod.string().optional().describe('The state after the transition'),
  "event": zod.object({
  "event_id": zod.string().uuid().optional().describe('The ID of the event that produced this record'),
  "sent_at": zod.string().datetime({"offset":true}).optional().describe('When the event was sent')
}).optional().describe('The event that triggered this transition'),
  "audit_metadata": zod.record(zod.string(), zod.unknown()).nullish().describe('Additional metadata recorded with the transition'),
  "created_at": zod.string().datetime({"offset":true}).optional()
})).optional(),
  "status_code": zod.number().int().optional().describe('The HTTP status code')
});

export type WorkflowAuditResponseSchema = zod.input<typeof WorkflowAuditResponseSchema>;
export type WorkflowAuditResponseSchemaOutput = zod.output<typeof WorkflowAuditResponseSchema>;

export const SortOrderWorkflowAuditPaginationSchema = zod.object({
  "order_by": zod.enum(['created_at']).describe('The field to sort the response by'),
  "sort_direction": zod.enum(['ascending', 'descending']).describe('Whether to sort the response ascending or descending')
});

export type SortOrderWorkflowAuditPaginationSchema = zod.input<typeof SortOrderWorkflowAuditPaginationSchema>;
export type SortOrderWorkflowAuditPaginationSchemaOutput = zod.output<typeof SortOrderWorkflowAuditPaginationSchema>;

export const workflowAuditPaginationSchemaSortOrderDefault = [{ order_by: 'created_at', sort_direction: 'descending', }];
export const workflowAuditPaginationSchemaSortOrderMax = 5;

export const workflowAuditPaginationSchemaPageSizeDefault = 25;
export const workflowAuditPaginationSchemaPageSizeMax = 5000;

export const workflowAuditPaginationSchemaPageOffsetDefault = 1;



export const WorkflowAuditPaginationSchema = zod.object({
  "sort_order": zod.array(zod.object({
  "order_by": zod.enum(['created_at']).describe('The field to sort the response by'),
  "sort_direction": zod.enum(['ascending', 'descending']).describe('Whether to sort the response ascending or descending')
})).min(1).max(workflowAuditPaginationSchemaSortOrderMax).default(workflowAuditPaginationSchemaSortOrderDefault).describe('The list of sorting rules'),
  "page_size": zod.number().int().min(1).max(workflowAuditPaginationSchemaPageSizeMax).default(workflowAuditPaginationSchemaPageSizeDefault).describe('The size of the page to fetch'),
  "page_offset": zod.number().int().min(1).default(workflowAuditPaginationSchemaPageOffsetDefault).describe('The page number to fetch, starts counting from 1')
});

export type WorkflowAuditPaginationSchema = zod.input<typeof WorkflowAuditPaginationSchema>;
export type WorkflowAuditPaginationSchemaOutput = zod.output<typeof WorkflowAuditPaginationSchema>;

export const workflowAuditRequestSchemaPaginationSortOrderDefault = [{ order_by: 'created_at', sort_direction: 'descending', }];
export const workflowAuditRequestSchemaPaginationSortOrderMax = 5;

export const workflowAuditRequestSchemaPaginationPageSizeDefault = 25;
export const workflowAuditRequestSchemaPaginationPageSizeMax = 5000;

export const workflowAuditRequestSchemaPaginationPageOffsetDefault = 1;



export const WorkflowAuditRequestSchema = zod.object({
  "pagination": zod.object({
  "sort_order": zod.array(zod.object({
  "order_by": zod.enum(['created_at']).describe('The field to sort the response by'),
  "sort_direction": zod.enum(['ascending', 'descending']).describe('Whether to sort the response ascending or descending')
})).min(1).max(workflowAuditRequestSchemaPaginationSortOrderMax).default(workflowAuditRequestSchemaPaginationSortOrderDefault).describe('The list of sorting rules'),
  "page_size": zod.number().int().min(1).max(workflowAuditRequestSchemaPaginationPageSizeMax).default(workflowAuditRequestSchemaPaginationPageSizeDefault).describe('The size of the page to fetch'),
  "page_offset": zod.number().int().min(1).default(workflowAuditRequestSchemaPaginationPageOffsetDefault).describe('The page number to fetch, starts counting from 1')
})
});

export type WorkflowAuditRequestSchema = zod.input<typeof WorkflowAuditRequestSchema>;
export type WorkflowAuditRequestSchemaOutput = zod.output<typeof WorkflowAuditRequestSchema>;

export const PartnerSchema1 = zod.object({
  "partner_id": zod.string().uuid().optional().describe('Unique ID of a partner'),
  "partner_name": zod.string().optional().describe('Name of the partner')
});

export type PartnerSchema1 = zod.input<typeof PartnerSchema1>;
export type PartnerSchema1Output = zod.output<typeof PartnerSchema1>;

export type GrantorOrganizationSchema = {
  /** Unique ID of a grantor organization */
  grantor_organization_id?: string;
  /** Name of the grantor organization */
  organization_name?: string;
  /** Type of grantor organization */
  grantor_organization_type?: string;
  partner?: PartnerSchema1;
  /** @nullable */
  parent_organization?: GrantorOrganizationSchema | null;
};

export const GrantorOrganizationSchema: zod.ZodType<GrantorOrganizationSchema> = zod.object({
  "grantor_organization_id": zod.string().uuid().optional().describe('Unique ID of a grantor organization'),
  "organization_name": zod.string().optional().describe('Name of the grantor organization'),
  "grantor_organization_type": zod.string().optional().describe('Type of grantor organization'),
  "partner": zod.object({
  "partner_id": zod.string().uuid().optional().describe('Unique ID of a partner'),
  "partner_name": zod.string().optional().describe('Name of the partner')
}).optional(),
  "parent_organization": zod.union([zod.lazy(() => GrantorOrganizationSchema),zod.null()]).nullish()
});

export type GrantorOrganizationSchemaOutput = zod.output<typeof GrantorOrganizationSchema>;

export const GetGrantorOrganizationResponseSchema = zod.object({
  "message": zod.string().optional().describe('The message to return'),
  "data": zod.object({
  "grantor_organization_id": zod.string().uuid().optional().describe('Unique ID of a grantor organization'),
  "organization_name": zod.string().optional().describe('Name of the grantor organization'),
  "grantor_organization_type": zod.string().optional().describe('Type of grantor organization'),
  "partner": zod.object({
  "partner_id": zod.string().uuid().optional().describe('Unique ID of a partner'),
  "partner_name": zod.string().optional().describe('Name of the partner')
}).optional(),
  "parent_organization": zod.union([zod.unknown(),zod.null()]).nullish()
}).optional(),
  "status_code": zod.number().int().optional().describe('The HTTP status code')
});

export type GetGrantorOrganizationResponseSchema = zod.input<typeof GetGrantorOrganizationResponseSchema>;
export type GetGrantorOrganizationResponseSchemaOutput = zod.output<typeof GetGrantorOrganizationResponseSchema>;

export const OpportunitySummarySchema = zod.object({
  "post_date": zod.string().date().nullish().describe('The date the opportunity was posted')
});

export type OpportunitySummarySchema = zod.input<typeof OpportunitySummarySchema>;
export type OpportunitySummarySchemaOutput = zod.output<typeof OpportunitySummarySchema>;

export const OpportunityDataSchema = zod.object({
  "opportunity_id": zod.string().uuid().describe('The unique identifier for the opportunity'),
  "opportunity_title": zod.string().nullish().describe('The title of the opportunity'),
  "opportunity_status": zod.enum(['forecasted', 'posted', 'closed', 'archived']).nullish().describe('The current status of the opportunity'),
  "summary": zod.union([OpportunitySummarySchema,zod.null()]).nullish().describe('Summary information about the opportunity')
});

export type OpportunityDataSchema = zod.input<typeof OpportunityDataSchema>;
export type OpportunityDataSchemaOutput = zod.output<typeof OpportunityDataSchema>;

export const OpportunityGetResponseSchema = zod.object({
  "data": zod.object({
  "opportunity_id": zod.string().uuid().describe('The unique identifier for the opportunity'),
  "opportunity_title": zod.string().nullish().describe('The title of the opportunity'),
  "opportunity_status": zod.enum(['forecasted', 'posted', 'closed', 'archived']).nullish().describe('The current status of the opportunity'),
  "summary": zod.union([zod.object({
  "post_date": zod.string().date().nullish().describe('The date the opportunity was posted')
}),zod.null()]).nullish().describe('Summary information about the opportunity')
}).optional().describe('The opportunity data')
});

export type OpportunityGetResponseSchema = zod.input<typeof OpportunityGetResponseSchema>;
export type OpportunityGetResponseSchemaOutput = zod.output<typeof OpportunityGetResponseSchema>;

export const ResourceForRoleSchema = zod.object({
  "resource_id": zod.string().uuid().optional().describe('The resource\'s unique identifier'),
  "resource_name": zod.string().nullish().describe('The resource\'s name, if its type has one')
});

export type ResourceForRoleSchema = zod.input<typeof ResourceForRoleSchema>;
export type ResourceForRoleSchemaOutput = zod.output<typeof ResourceForRoleSchema>;

export const RoleForUserSchema = zod.object({
  "role_id": zod.string().uuid().optional().describe('The role\'s unique identifier'),
  "role_name": zod.string().optional().describe('The role\'s name'),
  "privileges": zod.array(zod.enum(['view_partner', 'update_partner', 'manage_partner_members', 'view_program', 'update_program', 'view_grantor_organization', 'update_grantor_organization', 'manage_grantor_organization_members', 'internal_workflow_event_send', 'unused_privilege_102', 'unused_privilege_103'])).optional().describe('The privileges the role carries'),
  "resource_type": zod.enum(['internal', 'partner', 'program', 'grantor_organization', 'opportunity']).optional().describe('The type of resource the role was granted on'),
  "resource": zod.object({
  "resource_id": zod.string().uuid().optional().describe('The resource\'s unique identifier'),
  "resource_name": zod.string().nullish().describe('The resource\'s name, if its type has one')
}).optional().describe('The resource the role was granted on')
});

export type RoleForUserSchema = zod.input<typeof RoleForUserSchema>;
export type RoleForUserSchemaOutput = zod.output<typeof RoleForUserSchema>;

export const UserForResourceSchema = zod.object({
  "user_id": zod.string().uuid().optional().describe('The user\'s unique identifier'),
  "email": zod.string().nullish().describe('The user\'s email address, null if they have no login'),
  "roles": zod.array(zod.object({
  "role_id": zod.string().uuid().optional().describe('The role\'s unique identifier'),
  "role_name": zod.string().optional().describe('The role\'s name'),
  "privileges": zod.array(zod.enum(['view_partner', 'update_partner', 'manage_partner_members', 'view_program', 'update_program', 'view_grantor_organization', 'update_grantor_organization', 'manage_grantor_organization_members', 'internal_workflow_event_send', 'unused_privilege_102', 'unused_privilege_103'])).optional().describe('The privileges the role carries'),
  "resource_type": zod.enum(['internal', 'partner', 'program', 'grantor_organization', 'opportunity']).optional().describe('The type of resource the role was granted on'),
  "resource": zod.object({
  "resource_id": zod.string().uuid().optional().describe('The resource\'s unique identifier'),
  "resource_name": zod.string().nullish().describe('The resource\'s name, if its type has one')
}).optional().describe('The resource the role was granted on')
})).optional().describe('The roles granting this user access to the resource')
});

export type UserForResourceSchema = zod.input<typeof UserForResourceSchema>;
export type UserForResourceSchemaOutput = zod.output<typeof UserForResourceSchema>;

export const ListUserForResourceResponseSchema = zod.object({
  "pagination_info": zod.object({
  "page_offset": zod.number().int().optional().describe('The page number that was fetched'),
  "page_size": zod.number().int().optional().describe('The size of the page fetched'),
  "total_records": zod.number().int().optional().describe('The total number of records fetchable'),
  "total_pages": zod.number().int().optional().describe('The total number of pages that can be fetched'),
  "sort_order": zod.array(zod.object({
  "order_by": zod.string().optional().describe('The field that the records were sorted by'),
  "sort_direction": zod.enum(['ascending', 'descending']).optional().describe('The direction the records are sorted')
})).optional().describe('The sort order passed in originally')
}).optional().describe('The pagination information for paginated endpoints'),
  "message": zod.string().optional().describe('The message to return'),
  "data": zod.array(zod.object({
  "user_id": zod.string().uuid().optional().describe('The user\'s unique identifier'),
  "email": zod.string().nullish().describe('The user\'s email address, null if they have no login'),
  "roles": zod.array(zod.object({
  "role_id": zod.string().uuid().optional().describe('The role\'s unique identifier'),
  "role_name": zod.string().optional().describe('The role\'s name'),
  "privileges": zod.array(zod.enum(['view_partner', 'update_partner', 'manage_partner_members', 'view_program', 'update_program', 'view_grantor_organization', 'update_grantor_organization', 'manage_grantor_organization_members', 'internal_workflow_event_send', 'unused_privilege_102', 'unused_privilege_103'])).optional().describe('The privileges the role carries'),
  "resource_type": zod.enum(['internal', 'partner', 'program', 'grantor_organization', 'opportunity']).optional().describe('The type of resource the role was granted on'),
  "resource": zod.object({
  "resource_id": zod.string().uuid().optional().describe('The resource\'s unique identifier'),
  "resource_name": zod.string().nullish().describe('The resource\'s name, if its type has one')
}).optional().describe('The resource the role was granted on')
})).optional().describe('The roles granting this user access to the resource')
})).optional().describe('The users with access to the resource'),
  "status_code": zod.number().int().optional().describe('The HTTP status code')
});

export type ListUserForResourceResponseSchema = zod.input<typeof ListUserForResourceResponseSchema>;
export type ListUserForResourceResponseSchemaOutput = zod.output<typeof ListUserForResourceResponseSchema>;




export const PrivilegeFilterSchema = zod.object({
  "one_of": zod.array(zod.enum(['view_partner', 'update_partner', 'manage_partner_members', 'view_program', 'update_program', 'view_grantor_organization', 'update_grantor_organization', 'manage_grantor_organization_members', 'internal_workflow_event_send', 'unused_privilege_102', 'unused_privilege_103'])).min(1).optional()
});

export type PrivilegeFilterSchema = zod.input<typeof PrivilegeFilterSchema>;
export type PrivilegeFilterSchemaOutput = zod.output<typeof PrivilegeFilterSchema>;




export const InheritanceFilterSchema = zod.object({
  "one_of": zod.array(zod.enum(['full', 'direct'])).min(1).optional()
});

export type InheritanceFilterSchema = zod.input<typeof InheritanceFilterSchema>;
export type InheritanceFilterSchemaOutput = zod.output<typeof InheritanceFilterSchema>;





export const ListUserForResourceFilterSchema = zod.object({
  "privilege": zod.object({
  "one_of": zod.array(zod.enum(['view_partner', 'update_partner', 'manage_partner_members', 'view_program', 'update_program', 'view_grantor_organization', 'update_grantor_organization', 'manage_grantor_organization_members', 'internal_workflow_event_send', 'unused_privilege_102', 'unused_privilege_103'])).min(1).optional()
}).optional().describe('Only return users holding these privileges on the resource. A user must hold every privilege given, though not necessarily all from the same role.'),
  "inheritance": zod.object({
  "one_of": zod.array(zod.enum(['full', 'direct'])).min(1).optional()
}).optional().describe('Whether to consider roles granted anywhere up the resource hierarchy (\'full\') or only on the resource itself (\'direct\'). Accepts a single value, and defaults to \'direct\'.')
});

export type ListUserForResourceFilterSchema = zod.input<typeof ListUserForResourceFilterSchema>;
export type ListUserForResourceFilterSchemaOutput = zod.output<typeof ListUserForResourceFilterSchema>;

export const SortOrderListUserForResourcePaginationSchema = zod.object({
  "order_by": zod.enum(['user_id', 'email']).describe('The field to sort the response by'),
  "sort_direction": zod.enum(['ascending', 'descending']).describe('Whether to sort the response ascending or descending')
});

export type SortOrderListUserForResourcePaginationSchema = zod.input<typeof SortOrderListUserForResourcePaginationSchema>;
export type SortOrderListUserForResourcePaginationSchemaOutput = zod.output<typeof SortOrderListUserForResourcePaginationSchema>;

export const listUserForResourcePaginationSchemaSortOrderDefault = [{ order_by: 'user_id', sort_direction: 'ascending', }];
export const listUserForResourcePaginationSchemaSortOrderMax = 5;

export const listUserForResourcePaginationSchemaPageSizeMax = 5000;




export const ListUserForResourcePaginationSchema = zod.object({
  "sort_order": zod.array(zod.object({
  "order_by": zod.enum(['user_id', 'email']).describe('The field to sort the response by'),
  "sort_direction": zod.enum(['ascending', 'descending']).describe('Whether to sort the response ascending or descending')
})).min(1).max(listUserForResourcePaginationSchemaSortOrderMax).default(listUserForResourcePaginationSchemaSortOrderDefault).describe('The list of sorting rules'),
  "page_size": zod.number().int().min(1).max(listUserForResourcePaginationSchemaPageSizeMax).describe('The size of the page to fetch'),
  "page_offset": zod.number().int().min(1).describe('The page number to fetch, starts counting from 1')
});

export type ListUserForResourcePaginationSchema = zod.input<typeof ListUserForResourcePaginationSchema>;
export type ListUserForResourcePaginationSchemaOutput = zod.output<typeof ListUserForResourcePaginationSchema>;



export const listUserForResourceRequestSchemaPaginationSortOrderDefault = [{ order_by: 'user_id', sort_direction: 'ascending', }];
export const listUserForResourceRequestSchemaPaginationSortOrderMax = 5;

export const listUserForResourceRequestSchemaPaginationPageSizeMax = 5000;




export const ListUserForResourceRequestSchema = zod.object({
  "filters": zod.object({
  "privilege": zod.object({
  "one_of": zod.array(zod.enum(['view_partner', 'update_partner', 'manage_partner_members', 'view_program', 'update_program', 'view_grantor_organization', 'update_grantor_organization', 'manage_grantor_organization_members', 'internal_workflow_event_send', 'unused_privilege_102', 'unused_privilege_103'])).min(1).optional()
}).optional().describe('Only return users holding these privileges on the resource. A user must hold every privilege given, though not necessarily all from the same role.'),
  "inheritance": zod.object({
  "one_of": zod.array(zod.enum(['full', 'direct'])).min(1).optional()
}).optional().describe('Whether to consider roles granted anywhere up the resource hierarchy (\'full\') or only on the resource itself (\'direct\'). Accepts a single value, and defaults to \'direct\'.')
}).optional(),
  "pagination": zod.object({
  "sort_order": zod.array(zod.object({
  "order_by": zod.enum(['user_id', 'email']).describe('The field to sort the response by'),
  "sort_direction": zod.enum(['ascending', 'descending']).describe('Whether to sort the response ascending or descending')
})).min(1).max(listUserForResourceRequestSchemaPaginationSortOrderMax).default(listUserForResourceRequestSchemaPaginationSortOrderDefault).describe('The list of sorting rules'),
  "page_size": zod.number().int().min(1).max(listUserForResourceRequestSchemaPaginationPageSizeMax).describe('The size of the page to fetch'),
  "page_offset": zod.number().int().min(1).describe('The page number to fetch, starts counting from 1')
})
});

export type ListUserForResourceRequestSchema = zod.input<typeof ListUserForResourceRequestSchema>;
export type ListUserForResourceRequestSchemaOutput = zod.output<typeof ListUserForResourceRequestSchema>;
/**
 * @summary Healthcheck endpoint - verifies database can be connected to and returns deploy metadata.
 */
export const GetHealthResponse = HealthcheckResponseSchema


/**
 *
 * To use this endpoint, click [this link](/v1/users/login) which will redirect
 * you to an OAuth provider where you can sign into an account.
 *
 * Do not try to use the execute option below as OpenAPI will not redirect your browser for you.
 *
 * The token you receive can then be set to the X-MGMT-Token header for authenticating with endpoints.
 * @summary User Login
 */
export const GetV1UsersLoginQueryParams = zod.object({
  "piv_required": zod.boolean().nullish().describe('Whether the user is required to use a PIV to login')
})

export const GetV1UsersLoginResponse = zod.void()


/**
 *
 * To use this endpoint, click [this link](/v1/users/logout) which will redirect you
 * to an OAuth provider where you can logout of your account in both our system and
 * the OAuth system.
 * @summary User Logout
 */
export const GetV1UsersLogoutResponse = zod.void()


/**
 * @summary Local Users Get
 */
export const GetLocalLocalUsersResponse = LocalUserTokenResponseSchema


/**
 * Trigger a new workflow or progress an existing one.
 * @summary Send Workflow Event
 */
export const PutV1WorkflowsEventsBody = WorkflowEventRequestSchema

export const PutV1WorkflowsEventsResponse = WorkflowEventResponseSchema


/**
 * @summary User Token Logout
 */
export const PostV1UsersTokenLogoutResponse = UserTokenLogoutResponseSchema


/**
 * @summary User Token Refresh
 */
export const PostV1UsersTokenRefreshResponse = UserTokenRefreshResponseSchema


/**
 * @summary Fetch a Partner
 */
export const GetV1PartnersPartnerIdParams = zod.object({
  "partner_id": zod.string()
})

export const GetV1PartnersPartnerIdResponse = GetPartnerResponseSchema


/**
 * Get a workflow's current state, audit history, approvals, and approval configuration.
 * @summary Get Workflow
 */
export const GetV1WorkflowsWorkflowIdParams = zod.object({
  "workflow_id": zod.string()
})

export const GetV1WorkflowsWorkflowIdResponse = WorkflowGetResponseSchema


/**
 * @summary Check whether the calling user can access a resource with the given privileges.
 */
export const PostV1UsersUserIdCanAccessParams = zod.object({
  "user_id": zod.string()
})

export const PostV1UsersUserIdCanAccessBody = UserCanAccessRequestSchema

export const PostV1UsersUserIdCanAccessResponse = UserCanAccessResponseSchema


/**
 * Get the same payload as Get Workflow, resolved from one of its event IDs.
 * @summary Get Workflow By Event ID
 */
export const GetV1WorkflowsEventsEventIdParams = zod.object({
  "event_id": zod.string()
})

export const GetV1WorkflowsEventsEventIdResponse = WorkflowGetResponseSchema


/**
 * Get a workflow's audit history, paginated.
 * @summary Get Workflow Audit History
 */
export const PostV1WorkflowsWorkflowIdAuditParams = zod.object({
  "workflow_id": zod.string()
})

export const PostV1WorkflowsWorkflowIdAuditBody = WorkflowAuditRequestSchema

export const PostV1WorkflowsWorkflowIdAuditResponse = WorkflowAuditResponseSchema


/**
 * @summary Fetch a Grantor Organization
 */
export const GetV1GrantorOrganizationsGrantorOrganizationIdParams = zod.object({
  "grantor_organization_id": zod.string()
})

export const GetV1GrantorOrganizationsGrantorOrganizationIdResponse = GetGrantorOrganizationResponseSchema


/**
 * Fetch an opportunity from Simpler Grants as a proof-of-concept of cross-service data transfer. This endpoint requires JWT or API key authentication but has no authorization enforcement.
 * @summary Opportunity Get Simpler Min
 */
export const GetAlphaProofOfConceptOpportunitiesOpportunityIdParams = zod.object({
  "opportunity_id": zod.string()
})

export const GetAlphaProofOfConceptOpportunitiesOpportunityIdResponse = OpportunityGetResponseSchema


/**
 * List the users who can access a resource, along with the roles that grant them access.
 * @summary List Users For Resource
 */
export const PostV1ResourcesResourceTypeResourceIdUsersListParams = zod.object({
  "resource_type": zod.string(),
  "resource_id": zod.string()
})

export const PostV1ResourcesResourceTypeResourceIdUsersListBody = ListUserForResourceRequestSchema

export const PostV1ResourcesResourceTypeResourceIdUsersListResponse = ListUserForResourceResponseSchema
