"""add competition tables

Revision ID: f70d3358d13d
Revises: 745922be07e3
Create Date: 2026-09-06 19:21:30.244459

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f70d3358d13d"
down_revision = "745922be07e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunity_attachment",
        sa.Column("opportunity_attachment_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("file_attachment_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_attachment_id"],
            ["grantor.file_attachment.file_attachment_id"],
            name=op.f("opportunity_attachment_file_attachment_id_file_attachment_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["grantor.opportunity.opportunity_id"],
            name=op.f("opportunity_attachment_opportunity_id_opportunity_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "opportunity_attachment_id", name=op.f("opportunity_attachment_pkey")
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("opportunity_attachment_file_attachment_id_idx"),
        "opportunity_attachment",
        ["file_attachment_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("opportunity_attachment_opportunity_id_idx"),
        "opportunity_attachment",
        ["opportunity_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "competition",
        sa.Column("competition_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("public_competition_id", sa.Text(), nullable=True),
        sa.Column("competition_title", sa.Text(), nullable=True),
        sa.Column("opening_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("closing_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("grace_period", sa.BigInteger(), nullable=True),
        sa.Column("contact_info", sa.Text(), nullable=True),
        sa.Column("opportunity_assistance_listing_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_assistance_listing_id"],
            ["grantor.opportunity_assistance_listing.opportunity_assistance_listing_id"],
            name=op.f(
                "competition_opportunity_assistance_listing_id_opportunity_assistance_listing_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["grantor.opportunity.opportunity_id"],
            name=op.f("competition_opportunity_id_opportunity_fkey"),
        ),
        sa.PrimaryKeyConstraint("competition_id", name=op.f("competition_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("competition_opportunity_id_idx"),
        "competition",
        ["opportunity_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "competition_form",
        sa.Column("competition_form_id", sa.UUID(), nullable=False),
        sa.Column("competition_id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["grantor.competition.competition_id"],
            name=op.f("competition_form_competition_id_competition_fkey"),
        ),
        sa.PrimaryKeyConstraint("competition_form_id", name=op.f("competition_form_pkey")),
        sa.UniqueConstraint(
            "competition_id", "form_id", name=op.f("competition_form_competition_id_uniq")
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("competition_form_competition_id_idx"),
        "competition_form",
        ["competition_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "competition_instruction",
        sa.Column("competition_instruction_id", sa.UUID(), nullable=False),
        sa.Column("competition_id", sa.UUID(), nullable=False),
        sa.Column("file_attachment_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["grantor.competition.competition_id"],
            name=op.f("competition_instruction_competition_id_competition_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["file_attachment_id"],
            ["grantor.file_attachment.file_attachment_id"],
            name=op.f("competition_instruction_file_attachment_id_file_attachment_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "competition_instruction_id", name=op.f("competition_instruction_pkey")
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("competition_instruction_competition_id_idx"),
        "competition_instruction",
        ["competition_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "link_competition_open_to_applicant",
        sa.Column("competition_id", sa.UUID(), nullable=False),
        sa.Column("competition_open_to_applicant_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["grantor.competition.competition_id"],
            name=op.f("link_competition_open_to_applicant_competition_id_competition_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["competition_open_to_applicant_id"],
            ["grantor.lk_competition_open_to_applicant.competition_open_to_applicant_id"],
            name=op.f(
                "link_competition_open_to_applicant_competition_open_to_applicant_id_lk_competition_open_to_applicant_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "competition_id",
            "competition_open_to_applicant_id",
            name=op.f("link_competition_open_to_applicant_pkey"),
        ),
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("link_competition_open_to_applicant", schema="grantor")
    op.drop_index(
        op.f("competition_instruction_competition_id_idx"),
        table_name="competition_instruction",
        schema="grantor",
    )
    op.drop_table("competition_instruction", schema="grantor")
    op.drop_index(
        op.f("competition_form_competition_id_idx"), table_name="competition_form", schema="grantor"
    )
    op.drop_table("competition_form", schema="grantor")
    op.drop_index(
        op.f("competition_opportunity_id_idx"), table_name="competition", schema="grantor"
    )
    op.drop_table("competition", schema="grantor")
    op.drop_index(
        op.f("opportunity_attachment_opportunity_id_idx"),
        table_name="opportunity_attachment",
        schema="grantor",
    )
    op.drop_index(
        op.f("opportunity_attachment_file_attachment_id_idx"),
        table_name="opportunity_attachment",
        schema="grantor",
    )
    op.drop_table("opportunity_attachment", schema="grantor")
    # ### end Alembic commands ###
