"""remove mgmt prefixes

Revision ID: c6e45e66a003
Revises: b91e35008f59
Create Date: 2026-08-13 12:59:03.735224

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c6e45e66a003"
down_revision = "b91e35008f59"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_approval_response_type",
        sa.Column("approval_response_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "approval_response_type_id", name=op.f("lk_approval_response_type_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "lk_approval_type",
        sa.Column("approval_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("approval_type_id", name=op.f("lk_approval_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_privilege",
        sa.Column("privilege_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("privilege_id", name=op.f("lk_privilege_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_resource_type",
        sa.Column("resource_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("resource_type_id", name=op.f("lk_resource_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_user_type",
        sa.Column("user_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_type_id", name=op.f("lk_user_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_workflow_type",
        sa.Column("workflow_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("workflow_type_id", name=op.f("lk_workflow_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "login_gov_state",
        sa.Column("login_gov_state_id", sa.UUID(), nullable=False),
        sa.Column("nonce", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("login_gov_state_id", name=op.f("login_gov_state_pkey")),
        schema="grantor",
    )
    op.create_table(
        "role",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("role_name", sa.Text(), nullable=False),
        sa.Column("is_core", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("role_id", name=op.f("role_pkey")),
        schema="grantor",
    )
    op.create_table(
        "link_role_privilege",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("privilege_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["privilege_id"],
            ["grantor.lk_privilege.privilege_id"],
            name=op.f("link_role_privilege_privilege_id_lk_privilege_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["grantor.role.role_id"],
            name=op.f("link_role_privilege_role_id_role_fkey"),
        ),
        sa.PrimaryKeyConstraint("role_id", "privilege_id", name=op.f("link_role_privilege_pkey")),
        schema="grantor",
    )
    op.create_table(
        "link_role_resource_type",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("resource_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resource_type_id"],
            ["grantor.lk_resource_type.resource_type_id"],
            name=op.f("link_role_resource_type_resource_type_id_lk_resource_type_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["grantor.role.role_id"],
            name=op.f("link_role_resource_type_role_id_role_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "role_id", "resource_type_id", name=op.f("link_role_resource_type_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "resource",
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("resource_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resource_type_id"],
            ["grantor.lk_resource_type.resource_type_id"],
            name=op.f("resource_resource_type_id_lk_resource_type_fkey"),
        ),
        sa.PrimaryKeyConstraint("resource_id", name=op.f("resource_pkey")),
        schema="grantor",
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("user_type_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_type_id"],
            ["grantor.lk_user_type.user_type_id"],
            name=op.f("user_user_type_id_lk_user_type_fkey"),
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("user_pkey")),
        schema="grantor",
    )
    op.create_table(
        "internal_resource",
        sa.Column("internal_resource_id", sa.UUID(), nullable=False),
        sa.Column("internal_resource_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["internal_resource_id"],
            ["grantor.resource.resource_id"],
            name=op.f("internal_resource_internal_resource_id_resource_fkey"),
        ),
        sa.PrimaryKeyConstraint("internal_resource_id", name=op.f("internal_resource_pkey")),
        schema="grantor",
    )
    op.create_table(
        "link_external_user",
        sa.Column("link_external_user_id", sa.UUID(), nullable=False),
        sa.Column("external_user_type_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("external_user_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["external_user_type_id"],
            ["grantor.lk_external_user_type.external_user_type_id"],
            name=op.f("link_external_user_external_user_type_id_lk_external_user_type_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["grantor.user.user_id"], name=op.f("link_external_user_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("link_external_user_id", name=op.f("link_external_user_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("link_external_user_email_idx"),
        "link_external_user",
        ["email"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("link_external_user_external_user_id_idx"),
        "link_external_user",
        ["external_user_id"],
        unique=True,
        schema="grantor",
    )
    op.create_index(
        op.f("link_external_user_external_user_type_id_idx"),
        "link_external_user",
        ["external_user_type_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("link_external_user_user_id_idx"),
        "link_external_user",
        ["user_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "resource_user",
        sa.Column("resource_user_id", sa.UUID(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["grantor.resource.resource_id"],
            name=op.f("resource_user_resource_id_resource_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["grantor.user.user_id"], name=op.f("resource_user_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("resource_user_id", name=op.f("resource_user_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("resource_user_resource_id_idx"),
        "resource_user",
        ["resource_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("resource_user_user_id_idx"),
        "resource_user",
        ["user_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "user_api_key",
        sa.Column("api_key_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("key_name", sa.Text(), nullable=False),
        sa.Column("key_id", sa.Text(), nullable=False, comment="AWS API Gateway key identifier"),
        sa.Column("last_used", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["grantor.user.user_id"], name=op.f("user_api_key_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("api_key_id", name=op.f("user_api_key_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("user_api_key_key_id_idx"), "user_api_key", ["key_id"], unique=True, schema="grantor"
    )
    op.create_index(
        op.f("user_api_key_user_id_idx"),
        "user_api_key",
        ["user_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "user_token_session",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["grantor.user.user_id"], name=op.f("user_token_session_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("user_id", "token_id", name=op.f("user_token_session_pkey")),
        schema="grantor",
    )
    op.create_table(
        "workflow",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("workflow_type_id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("current_workflow_state", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["grantor.resource.resource_id"],
            name=op.f("workflow_resource_id_resource_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_type_id"],
            ["grantor.lk_workflow_type.workflow_type_id"],
            name=op.f("workflow_workflow_type_id_lk_workflow_type_fkey"),
        ),
        sa.PrimaryKeyConstraint("workflow_id", name=op.f("workflow_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("workflow_resource_id_idx"),
        "workflow",
        ["resource_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "resource_user_role",
        sa.Column("resource_user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resource_user_id"],
            ["grantor.resource_user.resource_user_id"],
            name=op.f("resource_user_role_resource_user_id_resource_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["grantor.role.role_id"], name=op.f("resource_user_role_role_id_role_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "resource_user_id", "role_id", name=op.f("resource_user_role_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "workflow_event_history",
        sa.Column("workflow_event_history_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=True),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sent_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_successfully_processed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["grantor.workflow.workflow_id"],
            name=op.f("workflow_event_history_workflow_id_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "workflow_event_history_id", name=op.f("workflow_event_history_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "workflow_approval",
        sa.Column("workflow_approval_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("approving_user_id", sa.UUID(), nullable=False),
        sa.Column("approval_type_id", sa.Integer(), nullable=False),
        sa.Column("workflow_event_history_id", sa.UUID(), nullable=False),
        sa.Column("is_still_valid", sa.Boolean(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("approval_response_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approval_response_type_id"],
            ["grantor.lk_approval_response_type.approval_response_type_id"],
            name=op.f("workflow_approval_approval_response_type_id_lk_approval_response_type_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["approval_type_id"],
            ["grantor.lk_approval_type.approval_type_id"],
            name=op.f("workflow_approval_approval_type_id_lk_approval_type_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["approving_user_id"],
            ["grantor.user.user_id"],
            name=op.f("workflow_approval_approving_user_id_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_event_history_id"],
            ["grantor.workflow_event_history.workflow_event_history_id"],
            name=op.f("workflow_approval_workflow_event_history_id_workflow_event_history_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["grantor.workflow.workflow_id"],
            name=op.f("workflow_approval_workflow_id_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint("workflow_approval_id", name=op.f("workflow_approval_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("workflow_approval_approval_response_type_id_idx"),
        "workflow_approval",
        ["approval_response_type_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("workflow_approval_approval_type_id_idx"),
        "workflow_approval",
        ["approval_type_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "workflow_audit",
        sa.Column("workflow_audit_id", sa.UUID(), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("acting_user_id", sa.UUID(), nullable=False),
        sa.Column("transition_event", sa.Text(), nullable=False),
        sa.Column("source_state", sa.Text(), nullable=False),
        sa.Column("target_state", sa.Text(), nullable=False),
        sa.Column("workflow_event_history_id", sa.UUID(), nullable=False),
        sa.Column("audit_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["acting_user_id"],
            ["grantor.user.user_id"],
            name=op.f("workflow_audit_acting_user_id_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_event_history_id"],
            ["grantor.workflow_event_history.workflow_event_history_id"],
            name=op.f("workflow_audit_workflow_event_history_id_workflow_event_history_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["grantor.workflow.workflow_id"],
            name=op.f("workflow_audit_workflow_id_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint("workflow_audit_id", name=op.f("workflow_audit_pkey")),
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_workflow_mgmt_resource_id_idx"), table_name="mgmt_workflow", schema="grantor"
    )

    op.drop_index(
        op.f("mgmt_resource_user_mgmt_resource_id_idx"),
        table_name="mgmt_resource_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_resource_user_mgmt_user_id_idx"),
        table_name="mgmt_resource_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_workflow_approval_mgmt_approval_response_type_id_idx"),
        table_name="mgmt_workflow_approval",
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_workflow_approval_mgmt_approval_type_id_idx"),
        table_name="mgmt_workflow_approval",
        schema="grantor",
    )

    op.drop_index(
        op.f("mgmt_link_external_user_email_idx"),
        table_name="mgmt_link_external_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_link_external_user_external_user_id_idx"),
        table_name="mgmt_link_external_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_link_external_user_external_user_type_id_idx"),
        table_name="mgmt_link_external_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_link_external_user_mgmt_user_id_idx"),
        table_name="mgmt_link_external_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_user_api_key_key_id_idx"), table_name="mgmt_user_api_key", schema="grantor"
    )
    op.drop_index(
        op.f("mgmt_user_api_key_mgmt_user_id_idx"), table_name="mgmt_user_api_key", schema="grantor"
    )
    op.drop_constraint(
        op.f("grantor_organization_grantor_organization_id_mgmt_resource_fkey"),
        "grantor_organization",
        schema="grantor",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("grantor_organization_grantor_organization_id_resource_fkey"),
        "grantor_organization",
        "resource",
        ["grantor_organization_id"],
        ["resource_id"],
        source_schema="grantor",
        referent_schema="grantor",
    )
    op.drop_constraint(
        op.f("partner_partner_id_mgmt_resource_fkey"),
        "partner",
        schema="grantor",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("partner_partner_id_resource_fkey"),
        "partner",
        "resource",
        ["partner_id"],
        ["resource_id"],
        source_schema="grantor",
        referent_schema="grantor",
    )

    op.create_foreign_key(
        op.f("program_program_id_resource_fkey"),
        "program",
        "resource",
        ["program_id"],
        ["resource_id"],
        source_schema="grantor",
        referent_schema="grantor",
    )

    op.drop_constraint(
        op.f("program_program_id_mgmt_resource_fkey"),
        "program",
        schema="grantor",
        type_="foreignkey",
    )

    op.drop_table("mgmt_login_gov_state", schema="grantor")
    op.drop_table("mgmt_link_role_privilege", schema="grantor")
    op.drop_table("mgmt_internal_resource", schema="grantor")
    op.drop_table("mgmt_workflow_approval", schema="grantor")
    op.drop_table("mgmt_workflow_audit", schema="grantor")
    op.drop_table("mgmt_workflow_event_history", schema="grantor")
    op.drop_table("mgmt_workflow", schema="grantor")
    op.drop_table("mgmt_link_external_user", schema="grantor")
    op.drop_table("mgmt_resource_user_role", schema="grantor")
    op.drop_table("mgmt_link_role_resource_type", schema="grantor")
    op.drop_table("mgmt_role", schema="grantor")
    op.drop_table("mgmt_resource_user", schema="grantor")
    op.drop_table("mgmt_resource", schema="grantor")
    op.drop_table("mgmt_user_api_key", schema="grantor")
    op.drop_table("mgmt_user_token_session", schema="grantor")
    op.drop_table("mgmt_user", schema="grantor")
    op.drop_table("lk_mgmt_workflow_type", schema="grantor")
    op.drop_table("lk_mgmt_user_type", schema="grantor")
    op.drop_table("lk_mgmt_approval_response_type", schema="grantor")
    op.drop_table("lk_mgmt_resource_type", schema="grantor")
    op.drop_table("lk_mgmt_approval_type", schema="grantor")
    op.drop_table("lk_mgmt_privilege", schema="grantor")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_mgmt_privilege",
        sa.Column("mgmt_privilege_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_privilege_id", name=op.f("lk_mgmt_privilege_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_mgmt_workflow_type",
        sa.Column("mgmt_workflow_type_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_workflow_type_id", name=op.f("lk_mgmt_workflow_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_mgmt_user_type",
        sa.Column("mgmt_user_type_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_user_type_id", name=op.f("lk_mgmt_user_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_mgmt_approval_response_type",
        sa.Column(
            "mgmt_approval_response_type_id", sa.INTEGER(), autoincrement=True, nullable=False
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_approval_response_type_id", name=op.f("lk_mgmt_approval_response_type_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "lk_mgmt_resource_type",
        sa.Column("mgmt_resource_type_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_resource_type_id", name=op.f("lk_mgmt_resource_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_mgmt_approval_type",
        sa.Column("mgmt_approval_type_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_approval_type_id", name=op.f("lk_mgmt_approval_type_pkey")),
        schema="grantor",
    )

    op.create_table(
        "mgmt_resource",
        sa.Column("mgmt_resource_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_resource_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_resource_type_id"],
            ["grantor.lk_mgmt_resource_type.mgmt_resource_type_id"],
            name=op.f("mgmt_resource_mgmt_resource_type_id_lk_mgmt_resource_type_fkey"),
        ),
        sa.PrimaryKeyConstraint("mgmt_resource_id", name=op.f("mgmt_resource_pkey")),
        schema="grantor",
    )

    op.create_table(
        "mgmt_role",
        sa.Column("mgmt_role_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("role_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_core", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_role_id", name=op.f("mgmt_role_pkey")),
        schema="grantor",
    )

    op.create_table(
        "mgmt_user",
        sa.Column("mgmt_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_user_type_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_user_type_id"],
            ["grantor.lk_mgmt_user_type.mgmt_user_type_id"],
            name=op.f("mgmt_user_mgmt_user_type_id_lk_mgmt_user_type_fkey"),
        ),
        sa.PrimaryKeyConstraint("mgmt_user_id", name=op.f("mgmt_user_pkey")),
        schema="grantor",
    )
    op.create_table(
        "mgmt_resource_user",
        sa.Column("mgmt_resource_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_resource_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_resource_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("mgmt_resource_user_mgmt_resource_id_mgmt_resource_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_user_id"],
            ["grantor.mgmt_user.mgmt_user_id"],
            name=op.f("mgmt_resource_user_mgmt_user_id_mgmt_user_fkey"),
        ),
        sa.PrimaryKeyConstraint("mgmt_resource_user_id", name=op.f("mgmt_resource_user_pkey")),
        schema="grantor",
    )
    op.create_table(
        "mgmt_resource_user_role",
        sa.Column("mgmt_resource_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_role_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_resource_user_id"],
            ["grantor.mgmt_resource_user.mgmt_resource_user_id"],
            name=op.f("mgmt_resource_user_role_mgmt_resource_user_id_mgmt_reso_c594"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_role_id"],
            ["grantor.mgmt_role.mgmt_role_id"],
            name=op.f("mgmt_resource_user_role_mgmt_role_id_mgmt_role_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_resource_user_id", "mgmt_role_id", name=op.f("mgmt_resource_user_role_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "mgmt_user_token_session",
        sa.Column("mgmt_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("token_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("is_valid", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_user_id"],
            ["grantor.mgmt_user.mgmt_user_id"],
            name=op.f("mgmt_user_token_session_mgmt_user_id_mgmt_user_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_user_id", "token_id", name=op.f("mgmt_user_token_session_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "mgmt_user_api_key",
        sa.Column("mgmt_api_key_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("key_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "key_id",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            comment="AWS API Gateway key identifier",
        ),
        sa.Column(
            "last_used", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_user_id"],
            ["grantor.mgmt_user.mgmt_user_id"],
            name=op.f("mgmt_user_api_key_mgmt_user_id_mgmt_user_fkey"),
        ),
        sa.PrimaryKeyConstraint("mgmt_api_key_id", name=op.f("mgmt_user_api_key_pkey")),
        schema="grantor",
    )
    op.create_table(
        "mgmt_workflow",
        sa.Column("mgmt_workflow_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_workflow_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("mgmt_resource_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("current_workflow_state", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_resource_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("mgmt_workflow_mgmt_resource_id_mgmt_resource_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_workflow_type_id"],
            ["grantor.lk_mgmt_workflow_type.mgmt_workflow_type_id"],
            name=op.f("mgmt_workflow_mgmt_workflow_type_id_lk_mgmt_workflow_type_fkey"),
        ),
        sa.PrimaryKeyConstraint("mgmt_workflow_id", name=op.f("mgmt_workflow_pkey")),
        schema="grantor",
    )
    op.create_table(
        "mgmt_workflow_event_history",
        sa.Column("mgmt_workflow_event_history_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_workflow_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "event_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "sent_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("is_successfully_processed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_workflow_id"],
            ["grantor.mgmt_workflow.mgmt_workflow_id"],
            name=op.f("mgmt_workflow_event_history_mgmt_workflow_id_mgmt_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_workflow_event_history_id", name=op.f("mgmt_workflow_event_history_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "mgmt_link_role_resource_type",
        sa.Column("mgmt_role_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_resource_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_resource_type_id"],
            ["grantor.lk_mgmt_resource_type.mgmt_resource_type_id"],
            name=op.f("mgmt_link_role_resource_type_mgmt_resource_type_id_lk_m_133b"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_role_id"],
            ["grantor.mgmt_role.mgmt_role_id"],
            name=op.f("mgmt_link_role_resource_type_mgmt_role_id_mgmt_role_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_role_id", "mgmt_resource_type_id", name=op.f("mgmt_link_role_resource_type_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "mgmt_workflow_audit",
        sa.Column("mgmt_workflow_audit_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_workflow_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("acting_mgmt_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("transition_event", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("source_state", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("target_state", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("mgmt_workflow_event_history_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "audit_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["acting_mgmt_user_id"],
            ["grantor.mgmt_user.mgmt_user_id"],
            name=op.f("mgmt_workflow_audit_acting_mgmt_user_id_mgmt_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_workflow_event_history_id"],
            ["grantor.mgmt_workflow_event_history.mgmt_workflow_event_history_id"],
            name=op.f("mgmt_workflow_audit_mgmt_workflow_event_history_id_mgmt_aac5"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_workflow_id"],
            ["grantor.mgmt_workflow.mgmt_workflow_id"],
            name=op.f("mgmt_workflow_audit_mgmt_workflow_id_mgmt_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint("mgmt_workflow_audit_id", name=op.f("mgmt_workflow_audit_pkey")),
        schema="grantor",
    )

    op.create_table(
        "mgmt_link_external_user",
        sa.Column("mgmt_link_external_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("external_user_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("mgmt_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("external_user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("email", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["external_user_type_id"],
            ["grantor.lk_external_user_type.external_user_type_id"],
            name=op.f("mgmt_link_external_user_external_user_type_id_lk_extern_c7a6"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_user_id"],
            ["grantor.mgmt_user.mgmt_user_id"],
            name=op.f("mgmt_link_external_user_mgmt_user_id_mgmt_user_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_link_external_user_id", name=op.f("mgmt_link_external_user_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "mgmt_workflow_approval",
        sa.Column("mgmt_workflow_approval_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_workflow_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("approving_mgmt_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_approval_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("mgmt_workflow_event_history_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("is_still_valid", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("comment", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "mgmt_approval_response_type_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approving_mgmt_user_id"],
            ["grantor.mgmt_user.mgmt_user_id"],
            name=op.f("mgmt_workflow_approval_approving_mgmt_user_id_mgmt_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_approval_response_type_id"],
            ["grantor.lk_mgmt_approval_response_type.mgmt_approval_response_type_id"],
            name=op.f("mgmt_workflow_approval_mgmt_approval_response_type_id_l_0ed8"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_approval_type_id"],
            ["grantor.lk_mgmt_approval_type.mgmt_approval_type_id"],
            name=op.f("mgmt_workflow_approval_mgmt_approval_type_id_lk_mgmt_ap_3ef7"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_workflow_event_history_id"],
            ["grantor.mgmt_workflow_event_history.mgmt_workflow_event_history_id"],
            name=op.f("mgmt_workflow_approval_mgmt_workflow_event_history_id_m_8697"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_workflow_id"],
            ["grantor.mgmt_workflow.mgmt_workflow_id"],
            name=op.f("mgmt_workflow_approval_mgmt_workflow_id_mgmt_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_workflow_approval_id", name=op.f("mgmt_workflow_approval_pkey")
        ),
        schema="grantor",
    )

    op.create_table(
        "mgmt_internal_resource",
        sa.Column("mgmt_internal_resource_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("internal_resource_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_internal_resource_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("mgmt_internal_resource_mgmt_internal_resource_id_mgmt_r_4c4f"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_internal_resource_id", name=op.f("mgmt_internal_resource_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "mgmt_link_role_privilege",
        sa.Column("mgmt_role_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("mgmt_privilege_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_privilege_id"],
            ["grantor.lk_mgmt_privilege.mgmt_privilege_id"],
            name=op.f("mgmt_link_role_privilege_mgmt_privilege_id_lk_mgmt_priv_ffa5"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_role_id"],
            ["grantor.mgmt_role.mgmt_role_id"],
            name=op.f("mgmt_link_role_privilege_mgmt_role_id_mgmt_role_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_role_id", "mgmt_privilege_id", name=op.f("mgmt_link_role_privilege_pkey")
        ),
        schema="grantor",
    )

    op.create_index(
        op.f("mgmt_workflow_mgmt_resource_id_idx"),
        "mgmt_workflow",
        ["mgmt_resource_id"],
        unique=False,
        schema="grantor",
    )

    op.create_table(
        "mgmt_login_gov_state",
        sa.Column("mgmt_login_gov_state_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("nonce", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_login_gov_state_id", name=op.f("mgmt_login_gov_state_pkey")),
        schema="grantor",
    )

    op.create_index(
        op.f("mgmt_workflow_approval_mgmt_approval_type_id_idx"),
        "mgmt_workflow_approval",
        ["mgmt_approval_type_id"],
        unique=False,
        schema="grantor",
    )

    op.drop_constraint(
        op.f("program_program_id_resource_fkey"), "program", schema="grantor", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("program_program_id_mgmt_resource_fkey"),
        "program",
        "mgmt_resource",
        ["program_id"],
        ["mgmt_resource_id"],
        source_schema="grantor",
        referent_schema="grantor",
    )
    op.drop_constraint(
        op.f("partner_partner_id_resource_fkey"), "partner", schema="grantor", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("partner_partner_id_mgmt_resource_fkey"),
        "partner",
        "mgmt_resource",
        ["partner_id"],
        ["mgmt_resource_id"],
        source_schema="grantor",
        referent_schema="grantor",
    )
    op.drop_constraint(
        op.f("grantor_organization_grantor_organization_id_resource_fkey"),
        "grantor_organization",
        schema="grantor",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("grantor_organization_grantor_organization_id_mgmt_resource_fkey"),
        "grantor_organization",
        "mgmt_resource",
        ["grantor_organization_id"],
        ["mgmt_resource_id"],
        source_schema="grantor",
        referent_schema="grantor",
    )

    op.create_index(
        op.f("mgmt_user_api_key_mgmt_user_id_idx"),
        "mgmt_user_api_key",
        ["mgmt_user_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_user_api_key_key_id_idx"),
        "mgmt_user_api_key",
        ["key_id"],
        unique=True,
        schema="grantor",
    )

    op.create_index(
        op.f("mgmt_link_external_user_mgmt_user_id_idx"),
        "mgmt_link_external_user",
        ["mgmt_user_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_link_external_user_external_user_type_id_idx"),
        "mgmt_link_external_user",
        ["external_user_type_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_link_external_user_external_user_id_idx"),
        "mgmt_link_external_user",
        ["external_user_id"],
        unique=True,
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_link_external_user_email_idx"),
        "mgmt_link_external_user",
        ["email"],
        unique=False,
        schema="grantor",
    )

    op.create_index(
        op.f("mgmt_workflow_approval_mgmt_approval_response_type_id_idx"),
        "mgmt_workflow_approval",
        ["mgmt_approval_response_type_id"],
        unique=False,
        schema="grantor",
    )

    op.create_index(
        op.f("mgmt_resource_user_mgmt_user_id_idx"),
        "mgmt_resource_user",
        ["mgmt_user_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_resource_user_mgmt_resource_id_idx"),
        "mgmt_resource_user",
        ["mgmt_resource_id"],
        unique=False,
        schema="grantor",
    )

    op.drop_table("workflow_audit", schema="grantor")
    op.drop_index(
        op.f("workflow_approval_approval_type_id_idx"),
        table_name="workflow_approval",
        schema="grantor",
    )
    op.drop_index(
        op.f("workflow_approval_approval_response_type_id_idx"),
        table_name="workflow_approval",
        schema="grantor",
    )
    op.drop_table("workflow_approval", schema="grantor")
    op.drop_table("workflow_event_history", schema="grantor")
    op.drop_table("resource_user_role", schema="grantor")
    op.drop_index(op.f("workflow_resource_id_idx"), table_name="workflow", schema="grantor")
    op.drop_table("workflow", schema="grantor")
    op.drop_table("user_token_session", schema="grantor")
    op.drop_index(op.f("user_api_key_user_id_idx"), table_name="user_api_key", schema="grantor")
    op.drop_index(op.f("user_api_key_key_id_idx"), table_name="user_api_key", schema="grantor")
    op.drop_table("user_api_key", schema="grantor")
    op.drop_index(op.f("resource_user_user_id_idx"), table_name="resource_user", schema="grantor")
    op.drop_index(
        op.f("resource_user_resource_id_idx"), table_name="resource_user", schema="grantor"
    )
    op.drop_table("resource_user", schema="grantor")
    op.drop_index(
        op.f("link_external_user_user_id_idx"), table_name="link_external_user", schema="grantor"
    )
    op.drop_index(
        op.f("link_external_user_external_user_type_id_idx"),
        table_name="link_external_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("link_external_user_external_user_id_idx"),
        table_name="link_external_user",
        schema="grantor",
    )
    op.drop_index(
        op.f("link_external_user_email_idx"), table_name="link_external_user", schema="grantor"
    )
    op.drop_table("link_external_user", schema="grantor")
    op.drop_table("internal_resource", schema="grantor")
    op.drop_table("user", schema="grantor")
    op.drop_table("resource", schema="grantor")
    op.drop_table("link_role_resource_type", schema="grantor")
    op.drop_table("link_role_privilege", schema="grantor")
    op.drop_table("role", schema="grantor")
    op.drop_table("login_gov_state", schema="grantor")
    op.drop_table("lk_workflow_type", schema="grantor")
    op.drop_table("lk_user_type", schema="grantor")
    op.drop_table("lk_resource_type", schema="grantor")
    op.drop_table("lk_privilege", schema="grantor")
    op.drop_table("lk_approval_type", schema="grantor")
    op.drop_table("lk_approval_response_type", schema="grantor")
    # ### end Alembic commands ###
