"""add task table

Revision ID: 83c8549b1ef0
Revises: 959c311ac64d
Create Date: 2026-09-02 15:03:28.687159

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "83c8549b1ef0"
down_revision = "959c311ac64d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_job_status",
        sa.Column("job_status_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("job_status_id", name=op.f("lk_job_status_pkey")),
        schema="grantor",
    )
    op.create_table(
        "job_log",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("job_type", sa.Text(), nullable=False),
        sa.Column("job_status_id", sa.Integer(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_status_id"],
            ["grantor.lk_job_status.job_status_id"],
            name=op.f("job_log_job_status_id_lk_job_status_fkey"),
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("job_log_pkey")),
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_log", schema="grantor")
    op.drop_table("lk_job_status", schema="grantor")
    # ### end Alembic commands ###
