"""add ltree extension

Revision ID: e6004a497a21
Revises: c6e45e66a003
Create Date: 2026-08-18 11:41:16.286886

"""

import sqlalchemy
from alembic import op

# revision identifiers, used by Alembic.
revision = "e6004a497a21"
down_revision = "c6e45e66a003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sqlalchemy.text("CREATE EXTENSION IF NOT EXISTS ltree;"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
