"""Create audit tables for partner & grantor organization

Revision ID: fc3b971ad196
Revises: e6004a497a21
Create Date: 2026-08-21 14:59:17.561563

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fc3b971ad196"
down_revision = "e6004a497a21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_grantor_organization_audit_event",
        sa.Column("grantor_organization_audit_event_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "grantor_organization_audit_event_id",
            name=op.f("lk_grantor_organization_audit_event_pkey"),
        ),
        schema="grantor",
    )
    op.create_table(
        "lk_partner_audit_event",
        sa.Column("partner_audit_event_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("partner_audit_event_id", name=op.f("lk_partner_audit_event_pkey")),
        schema="grantor",
    )
    op.create_table(
        "partner_audit",
        sa.Column("partner_audit_id", sa.UUID(), nullable=False),
        sa.Column("partner_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("partner_audit_event_id", sa.Integer(), nullable=False),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column("audit_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["partner_audit_event_id"],
            ["grantor.lk_partner_audit_event.partner_audit_event_id"],
            name=op.f("partner_audit_partner_audit_event_id_lk_partner_audit_event_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["grantor.partner.partner_id"],
            name=op.f("partner_audit_partner_id_partner_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["grantor.user.user_id"],
            name=op.f("partner_audit_target_user_id_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["grantor.user.user_id"], name=op.f("partner_audit_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("partner_audit_id", name=op.f("partner_audit_pkey")),
        schema="grantor",
    )
    op.create_table(
        "grantor_organization_audit",
        sa.Column("grantor_organization_audit_id", sa.UUID(), nullable=False),
        sa.Column("grantor_organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("grantor_organization_audit_event_id", sa.Integer(), nullable=False),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column("audit_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grantor_organization_audit_event_id"],
            ["grantor.lk_grantor_organization_audit_event.grantor_organization_audit_event_id"],
            name=op.f(
                "grantor_organization_audit_grantor_organization_audit_event_id_lk_grantor_organization_audit_event_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["grantor_organization_id"],
            ["grantor.grantor_organization.grantor_organization_id"],
            name=op.f(
                "grantor_organization_audit_grantor_organization_id_grantor_organization_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["grantor.user.user_id"],
            name=op.f("grantor_organization_audit_target_user_id_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["grantor.user.user_id"],
            name=op.f("grantor_organization_audit_user_id_user_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "grantor_organization_audit_id", name=op.f("grantor_organization_audit_pkey")
        ),
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grantor_organization_audit", schema="grantor")
    op.drop_table("partner_audit", schema="grantor")
    op.drop_table("lk_partner_audit_event", schema="grantor")
    op.drop_table("lk_grantor_organization_audit_event", schema="grantor")
    # ### end Alembic commands ###
