"""fix column names

Revision ID: 74587e523544
Revises: fc3b971ad196
Create Date: 2026-08-31 09:25:03.849387

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "74587e523544"
down_revision = "fc3b971ad196"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grantor_organization_audit",
        sa.Column("grantor_organization_audit_event_id", sa.Integer(), nullable=False),
        schema="grantor",
    )
    op.drop_constraint(
        op.f("grantor_organization_audit_grantor_organization_audit_e_ebbf"),
        "grantor_organization_audit",
        schema="grantor",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f(
            "grantor_organization_audit_grantor_organization_audit_event_id_lk_grantor_organization_audit_event_fkey"
        ),
        "grantor_organization_audit",
        "lk_grantor_organization_audit_event",
        ["grantor_organization_audit_event_id"],
        ["grantor_organization_audit_event_id"],
        source_schema="grantor",
        referent_schema="grantor",
    )
    op.drop_column(
        "grantor_organization_audit", "grantor_organization_audit_event", schema="grantor"
    )
    op.add_column(
        "partner_audit",
        sa.Column("partner_audit_event_id", sa.Integer(), nullable=False),
        schema="grantor",
    )
    op.drop_constraint(
        op.f("partner_audit_partner_audit_event_lk_partner_audit_event_fkey"),
        "partner_audit",
        schema="grantor",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("partner_audit_partner_audit_event_id_lk_partner_audit_event_fkey"),
        "partner_audit",
        "lk_partner_audit_event",
        ["partner_audit_event_id"],
        ["partner_audit_event_id"],
        source_schema="grantor",
        referent_schema="grantor",
    )
    op.drop_column("partner_audit", "partner_audit_event", schema="grantor")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "partner_audit",
        sa.Column("partner_audit_event", sa.INTEGER(), autoincrement=False, nullable=False),
        schema="grantor",
    )
    op.drop_constraint(
        op.f("partner_audit_partner_audit_event_id_lk_partner_audit_event_fkey"),
        "partner_audit",
        schema="grantor",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("partner_audit_partner_audit_event_lk_partner_audit_event_fkey"),
        "partner_audit",
        "lk_partner_audit_event",
        ["partner_audit_event"],
        ["partner_audit_event_id"],
        source_schema="grantor",
        referent_schema="grantor",
    )
    op.drop_column("partner_audit", "partner_audit_event_id", schema="grantor")
    op.add_column(
        "grantor_organization_audit",
        sa.Column(
            "grantor_organization_audit_event", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        schema="grantor",
    )
    op.drop_constraint(
        op.f(
            "grantor_organization_audit_grantor_organization_audit_event_id_lk_grantor_organization_audit_event_fkey"
        ),
        "grantor_organization_audit",
        schema="grantor",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("grantor_organization_audit_grantor_organization_audit_e_ebbf"),
        "grantor_organization_audit",
        "lk_grantor_organization_audit_event",
        ["grantor_organization_audit_event"],
        ["grantor_organization_audit_event_id"],
        source_schema="grantor",
        referent_schema="grantor",
    )
    op.drop_column(
        "grantor_organization_audit", "grantor_organization_audit_event_id", schema="grantor"
    )
    # ### end Alembic commands ###
