"""add opportunity lookup tables

Revision ID: d4ef6a4f0564
Revises: 959c311ac64d
Create Date: 2026-09-06 17:00:30.694860

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d4ef6a4f0564"
down_revision = "959c311ac64d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
