"""add opportunity lookup tables

Revision ID: 33b8938e3b68
Revises: 959c311ac64d
Create Date: 2026-09-06 17:20:56.366488

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "33b8938e3b68"
down_revision = "83c8549b1ef0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_applicant_type",
        sa.Column("applicant_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("applicant_type_id", name=op.f("lk_applicant_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_competition_open_to_applicant",
        sa.Column("competition_open_to_applicant_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "competition_open_to_applicant_id", name=op.f("lk_competition_open_to_applicant_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "lk_funding_category",
        sa.Column("funding_category_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("funding_category_id", name=op.f("lk_funding_category_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_funding_instrument",
        sa.Column("funding_instrument_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("funding_instrument_id", name=op.f("lk_funding_instrument_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_opportunity_audit_event",
        sa.Column("opportunity_audit_event_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "opportunity_audit_event_id", name=op.f("lk_opportunity_audit_event_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "lk_opportunity_category",
        sa.Column("opportunity_category_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "opportunity_category_id", name=op.f("lk_opportunity_category_pkey")
        ),
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lk_opportunity_category", schema="grantor")
    op.drop_table("lk_opportunity_audit_event", schema="grantor")
    op.drop_table("lk_funding_instrument", schema="grantor")
    op.drop_table("lk_funding_category", schema="grantor")
    op.drop_table("lk_competition_open_to_applicant", schema="grantor")
    op.drop_table("lk_applicant_type", schema="grantor")
    # ### end Alembic commands ###
