"""add program hierarchy

Revision ID: 1b38b0f440be
Revises: a629d287817e
Create Date: 2026-08-06 12:53:09.851565

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1b38b0f440be"
down_revision = "a629d287817e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_grantor_organization_type",
        sa.Column("grantor_organization_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "grantor_organization_type_id", name=op.f("lk_grantor_organization_type_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "partner",
        sa.Column("partner_id", sa.UUID(), nullable=False),
        sa.Column("partner_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("partner_partner_id_mgmt_resource_fkey"),
        ),
        sa.PrimaryKeyConstraint("partner_id", name=op.f("partner_pkey")),
        schema="grantor",
    )
    op.create_table(
        "grantor_organization",
        sa.Column("grantor_organization_id", sa.UUID(), nullable=False),
        sa.Column("organization_name", sa.Text(), nullable=False),
        sa.Column("partner_id", sa.UUID(), nullable=False),
        sa.Column("parent_organization_id", sa.UUID(), nullable=True),
        sa.Column("grantor_organization_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grantor_organization_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("grantor_organization_grantor_organization_id_mgmt_resource_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["grantor_organization_type_id"],
            ["grantor.lk_grantor_organization_type.grantor_organization_type_id"],
            name=op.f(
                "grantor_organization_grantor_organization_type_id_lk_grantor_organization_type_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["parent_organization_id"],
            ["grantor.grantor_organization.grantor_organization_id"],
            name=op.f("grantor_organization_parent_organization_id_grantor_organization_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["grantor.partner.partner_id"],
            name=op.f("grantor_organization_partner_id_partner_fkey"),
        ),
        sa.PrimaryKeyConstraint("grantor_organization_id", name=op.f("grantor_organization_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("grantor_organization_parent_organization_id_idx"),
        "grantor_organization",
        ["parent_organization_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("grantor_organization_partner_id_idx"),
        "grantor_organization",
        ["partner_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "program",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("program_name", sa.Text(), nullable=False),
        sa.Column("partner_id", sa.UUID(), nullable=False),
        sa.Column("program_office_id", sa.UUID(), nullable=False),
        sa.Column("grant_office_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grant_office_id"],
            ["grantor.grantor_organization.grantor_organization_id"],
            name=op.f("program_grant_office_id_grantor_organization_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["grantor.partner.partner_id"],
            name=op.f("program_partner_id_partner_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("program_program_id_mgmt_resource_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["program_office_id"],
            ["grantor.grantor_organization.grantor_organization_id"],
            name=op.f("program_program_office_id_grantor_organization_fkey"),
        ),
        sa.PrimaryKeyConstraint("program_id", name=op.f("program_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("program_grant_office_id_idx"),
        "program",
        ["grant_office_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("program_partner_id_idx"), "program", ["partner_id"], unique=False, schema="grantor"
    )
    op.create_index(
        op.f("program_program_office_id_idx"),
        "program",
        ["program_office_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "secondary_program_partner",
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("partner_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["grantor.partner.partner_id"],
            name=op.f("secondary_program_partner_partner_id_partner_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["grantor.program.program_id"],
            name=op.f("secondary_program_partner_program_id_program_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "program_id", "partner_id", name=op.f("secondary_program_partner_pkey")
        ),
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("secondary_program_partner", schema="grantor")
    op.drop_index(op.f("program_program_office_id_idx"), table_name="program", schema="grantor")
    op.drop_index(op.f("program_partner_id_idx"), table_name="program", schema="grantor")
    op.drop_index(op.f("program_grant_office_id_idx"), table_name="program", schema="grantor")
    op.drop_table("program", schema="grantor")
    op.drop_index(
        op.f("grantor_organization_partner_id_idx"),
        table_name="grantor_organization",
        schema="grantor",
    )
    op.drop_index(
        op.f("grantor_organization_parent_organization_id_idx"),
        table_name="grantor_organization",
        schema="grantor",
    )
    op.drop_table("grantor_organization", schema="grantor")
    op.drop_table("partner", schema="grantor")
    op.drop_table("lk_grantor_organization_type", schema="grantor")
    # ### end Alembic commands ###
