"""add program title index

Revision ID: 8d1ad26e7f9d
Revises: 83c8549b1ef0
Create Date: 2026-09-08 10:52:28.358988

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8d1ad26e7f9d"
down_revision = "83c8549b1ef0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_v_assistance_listing_program_title",
        "assistance_listing",
        [sa.literal_column("to_tsvector('english', program_title)")],
        unique=False,
        schema="grantor",
        postgresql_using="GIN",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_v_assistance_listing_program_title",
        table_name="assistance_listing",
        schema="grantor",
        postgresql_using="GIN",
    )
    # ### end Alembic commands ###
