"""Remove tables for authZ no longer needed

Revision ID: a629d287817e
Revises: cc73f991a327
Create Date: 2026-08-05 16:45:58.721985

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a629d287817e"
down_revision = "cc73f991a327"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team", schema="grantor")
    op.drop_table("subagency", schema="grantor")
    op.drop_table("department", schema="grantor")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "department",
        sa.Column("department_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("department_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("department_department_id_mgmt_resource_fkey"),
        ),
        sa.PrimaryKeyConstraint("department_id", name=op.f("department_pkey")),
        schema="grantor",
    )
    op.create_table(
        "subagency",
        sa.Column("subagency_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("subagency_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("department_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["grantor.department.department_id"],
            name=op.f("subagency_department_id_department_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["subagency_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("subagency_subagency_id_mgmt_resource_fkey"),
        ),
        sa.PrimaryKeyConstraint("subagency_id", name=op.f("subagency_pkey")),
        schema="grantor",
    )
    op.create_table(
        "team",
        sa.Column("team_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("team_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("subagency_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subagency_id"],
            ["grantor.subagency.subagency_id"],
            name=op.f("team_subagency_id_subagency_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("team_team_id_mgmt_resource_fkey"),
        ),
        sa.PrimaryKeyConstraint("team_id", name=op.f("team_pkey")),
        schema="grantor",
    )
    # ### end Alembic commands ###
