"""add assistance listing table

Revision ID: 959c311ac64d
Revises: 9998d48622ed
Create Date: 2026-09-01 21:27:14.320856

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "959c311ac64d"
down_revision = "9998d48622ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistance_listing",
        sa.Column("assistance_listing_id", sa.UUID(), nullable=False),
        sa.Column("assistance_listing_number", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("published_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("program_title", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("assistance_listing_id", name=op.f("assistance_listing_pkey")),
        sa.UniqueConstraint(
            "assistance_listing_number",
            name=op.f("assistance_listing_assistance_listing_number_uniq"),
        ),
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assistance_listing", schema="grantor")
    # ### end Alembic commands ###
