"""Create Opportunity Base Record Model

Revision ID: 38549d7016ca
Revises: 4b7e2c9d1a63
Create Date: 2026-10-06 20:57:36.091829

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "38549d7016ca"
down_revision = "4b7e2c9d1a63"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunity",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("partner_code", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("opportunity_id", name=op.f("opportunity_pkey")),
        schema="grantor",
    )
    op.add_column(
        "announcement", sa.Column("opportunity_id", sa.UUID(), nullable=False), schema="grantor"
    )
    op.create_index(
        op.f("announcement_opportunity_id_idx"),
        "announcement",
        ["opportunity_id"],
        unique=False,
        schema="grantor",
    )
    op.create_foreign_key(
        op.f("announcement_opportunity_id_opportunity_fkey"),
        "announcement",
        "opportunity",
        ["opportunity_id"],
        ["opportunity_id"],
        source_schema="grantor",
        referent_schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("announcement_opportunity_id_opportunity_fkey"),
        "announcement",
        schema="grantor",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("announcement_opportunity_id_idx"), table_name="announcement", schema="grantor"
    )
    op.drop_column("announcement", "opportunity_id", schema="grantor")
    op.drop_table("opportunity", schema="grantor")
    # ### end Alembic commands ###
