"""add soft deletes

Revision ID: 058f456bcef7
Revises: 48d36e0698ce
Create Date: 2026-09-21 11:01:30.348768

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "058f456bcef7"
down_revision = "48d36e0698ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcement",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        schema="grantor",
    )
    op.create_index(
        op.f("announcement_is_deleted_idx"),
        "announcement",
        ["is_deleted"],
        unique=False,
        schema="grantor",
    )
    op.add_column(
        "announcement_attachment",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        schema="grantor",
    )
    op.create_index(
        op.f("announcement_attachment_is_deleted_idx"),
        "announcement_attachment",
        ["is_deleted"],
        unique=False,
        schema="grantor",
    )
    op.add_column(
        "announcement_summary",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        schema="grantor",
    )
    op.drop_constraint(
        op.f("announcement_summary_is_forecast_uniq"),
        "announcement_summary",
        schema="grantor",
        type_="unique",
    )
    op.create_index(
        op.f("announcement_summary_is_deleted_idx"),
        "announcement_summary",
        ["is_deleted"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        "announcement_summary_is_forecast_idx",
        "announcement_summary",
        ["is_forecast", "announcement_id"],
        unique=True,
        schema="grantor",
        postgresql_where="is_deleted = false",
    )
    op.add_column(
        "application_package",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        schema="grantor",
    )
    op.create_index(
        op.f("application_package_is_deleted_idx"),
        "application_package",
        ["is_deleted"],
        unique=False,
        schema="grantor",
    )
    op.add_column(
        "application_package_instruction",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        schema="grantor",
    )
    op.create_index(
        op.f("application_package_instruction_is_deleted_idx"),
        "application_package_instruction",
        ["is_deleted"],
        unique=False,
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("application_package_instruction_is_deleted_idx"),
        table_name="application_package_instruction",
        schema="grantor",
    )
    op.drop_column("application_package_instruction", "is_deleted", schema="grantor")
    op.drop_index(
        op.f("application_package_is_deleted_idx"),
        table_name="application_package",
        schema="grantor",
    )
    op.drop_column("application_package", "is_deleted", schema="grantor")
    op.drop_index(
        "announcement_summary_is_forecast_idx",
        table_name="announcement_summary",
        schema="grantor",
        postgresql_where="is_deleted = false",
    )
    op.drop_index(
        op.f("announcement_summary_is_deleted_idx"),
        table_name="announcement_summary",
        schema="grantor",
    )
    op.create_unique_constraint(
        op.f("announcement_summary_is_forecast_uniq"),
        "announcement_summary",
        ["is_forecast", "announcement_id"],
        schema="grantor",
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("announcement_summary", "is_deleted", schema="grantor")
    op.drop_index(
        op.f("announcement_attachment_is_deleted_idx"),
        table_name="announcement_attachment",
        schema="grantor",
    )
    op.drop_column("announcement_attachment", "is_deleted", schema="grantor")
    op.drop_index(op.f("announcement_is_deleted_idx"), table_name="announcement", schema="grantor")
    op.drop_column("announcement", "is_deleted", schema="grantor")
    # ### end Alembic commands ###
