"""add opportunity core tables

Revision ID: 97ec15d7034c
Revises: 33b8938e3b68
Create Date: 2026-09-06 17:57:46.304522

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "97ec15d7034c"
down_revision = "33b8938e3b68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunity_group",
        sa.Column("opportunity_group_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_group_id"],
            ["grantor.resource.resource_id"],
            name=op.f("opportunity_group_opportunity_group_id_resource_fkey"),
        ),
        sa.PrimaryKeyConstraint("opportunity_group_id", name=op.f("opportunity_group_pkey")),
        schema="grantor",
    )
    op.create_table(
        "opportunity",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_group_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_number", sa.Text(), nullable=False),
        sa.Column("opportunity_title", sa.Text(), nullable=False),
        sa.Column("tagline", sa.Text(), nullable=False),
        sa.Column("purpose_statement", sa.Text(), nullable=False),
        sa.Column("opportunity_category_id", sa.Integer(), nullable=True),
        sa.Column("category_explanation", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_category_id"],
            ["grantor.lk_opportunity_category.opportunity_category_id"],
            name=op.f("opportunity_opportunity_category_id_lk_opportunity_category_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_group_id"],
            ["grantor.opportunity_group.opportunity_group_id"],
            name=op.f("opportunity_opportunity_group_id_opportunity_group_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["grantor.resource.resource_id"],
            name=op.f("opportunity_opportunity_id_resource_fkey"),
        ),
        sa.PrimaryKeyConstraint("opportunity_id", name=op.f("opportunity_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("opportunity_opportunity_category_id_idx"),
        "opportunity",
        ["opportunity_category_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("opportunity_opportunity_group_id_idx"),
        "opportunity",
        ["opportunity_group_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "opportunity_assistance_listing",
        sa.Column("opportunity_assistance_listing_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("assistance_listing_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assistance_listing_id"],
            ["grantor.assistance_listing.assistance_listing_id"],
            name=op.f(
                "opportunity_assistance_listing_assistance_listing_id_assistance_listing_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["grantor.opportunity.opportunity_id"],
            name=op.f("opportunity_assistance_listing_opportunity_id_opportunity_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "opportunity_assistance_listing_id", name=op.f("opportunity_assistance_listing_pkey")
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("opportunity_assistance_listing_assistance_listing_id_idx"),
        "opportunity_assistance_listing",
        ["assistance_listing_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("opportunity_assistance_listing_opportunity_id_idx"),
        "opportunity_assistance_listing",
        ["opportunity_id"],
        unique=False,
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("opportunity_assistance_listing_opportunity_id_idx"),
        table_name="opportunity_assistance_listing",
        schema="grantor",
    )
    op.drop_index(
        op.f("opportunity_assistance_listing_assistance_listing_id_idx"),
        table_name="opportunity_assistance_listing",
        schema="grantor",
    )
    op.drop_table("opportunity_assistance_listing", schema="grantor")
    op.drop_index(
        op.f("opportunity_opportunity_group_id_idx"), table_name="opportunity", schema="grantor"
    )
    op.drop_index(
        op.f("opportunity_opportunity_category_id_idx"), table_name="opportunity", schema="grantor"
    )
    op.drop_table("opportunity", schema="grantor")
    op.drop_table("opportunity_group", schema="grantor")
    # ### end Alembic commands ###
