"""add announcement and application package tables

Revision ID: 713252ec479c
Revises: 8d1ad26e7f9d
Create Date: 2026-09-10 14:11:16.928598

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "713252ec479c"
down_revision = "8d1ad26e7f9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_announcement_audit_event",
        sa.Column("announcement_audit_event_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "announcement_audit_event_id", name=op.f("lk_announcement_audit_event_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "lk_announcement_category",
        sa.Column("announcement_category_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "announcement_category_id", name=op.f("lk_announcement_category_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "lk_applicant_type",
        sa.Column("applicant_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("applicant_type_id", name=op.f("lk_applicant_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_application_package_open_to_applicant",
        sa.Column("application_package_open_to_applicant_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "application_package_open_to_applicant_id",
            name=op.f("lk_application_package_open_to_applicant_pkey"),
        ),
        schema="grantor",
    )
    op.create_table(
        "lk_form_family",
        sa.Column("form_family_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("form_family_id", name=op.f("lk_form_family_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_funding_category",
        sa.Column("funding_category_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("funding_category_id", name=op.f("lk_funding_category_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_funding_instrument",
        sa.Column("funding_instrument_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("funding_instrument_id", name=op.f("lk_funding_instrument_pkey")),
        schema="grantor",
    )
    op.create_table(
        "announcement",
        sa.Column("announcement_id", sa.UUID(), nullable=False),
        sa.Column("announcement_number", sa.Text(), nullable=False),
        sa.Column("announcement_title", sa.Text(), nullable=False),
        sa.Column("tagline", sa.Text(), nullable=True),
        sa.Column("purpose_statement", sa.Text(), nullable=True),
        sa.Column("announcement_category_id", sa.Integer(), nullable=True),
        sa.Column("category_explanation", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_category_id"],
            ["grantor.lk_announcement_category.announcement_category_id"],
            name=op.f("announcement_announcement_category_id_lk_announcement_category_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["grantor.resource.resource_id"],
            name=op.f("announcement_announcement_id_resource_fkey"),
        ),
        sa.PrimaryKeyConstraint("announcement_id", name=op.f("announcement_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("announcement_announcement_category_id_idx"),
        "announcement",
        ["announcement_category_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "announcement_assistance_listing",
        sa.Column("announcement_assistance_listing_id", sa.UUID(), nullable=False),
        sa.Column("announcement_id", sa.UUID(), nullable=False),
        sa.Column("assistance_listing_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["grantor.announcement.announcement_id"],
            name=op.f("announcement_assistance_listing_announcement_id_announcement_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["assistance_listing_id"],
            ["grantor.assistance_listing.assistance_listing_id"],
            name=op.f(
                "announcement_assistance_listing_assistance_listing_id_assistance_listing_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "announcement_assistance_listing_id", name=op.f("announcement_assistance_listing_pkey")
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("announcement_assistance_listing_announcement_id_idx"),
        "announcement_assistance_listing",
        ["announcement_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("announcement_assistance_listing_assistance_listing_id_idx"),
        "announcement_assistance_listing",
        ["assistance_listing_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "announcement_summary",
        sa.Column("announcement_summary_id", sa.UUID(), nullable=False),
        sa.Column("announcement_id", sa.UUID(), nullable=False),
        sa.Column("summary_description", sa.Text(), nullable=False),
        sa.Column("is_cost_sharing", sa.Boolean(), nullable=False),
        sa.Column("is_forecast", sa.Boolean(), nullable=False),
        sa.Column("post_timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("close_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("close_timestamp_description", sa.Text(), nullable=True),
        sa.Column("archive_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("expected_number_of_awards", sa.BigInteger(), nullable=True),
        sa.Column("estimated_total_program_funding", sa.BigInteger(), nullable=True),
        sa.Column("award_floor", sa.BigInteger(), nullable=True),
        sa.Column("award_ceiling", sa.BigInteger(), nullable=True),
        sa.Column("additional_info_url", sa.Text(), nullable=True),
        sa.Column("additional_info_url_description", sa.Text(), nullable=True),
        sa.Column("forecasted_post_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("forecasted_close_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("forecasted_close_timestamp_description", sa.Text(), nullable=True),
        sa.Column("estimated_award_date", sa.Date(), nullable=True),
        sa.Column("estimated_project_start_date", sa.Date(), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("funding_category_description", sa.Text(), nullable=True),
        sa.Column("applicant_eligibility_description", sa.Text(), nullable=True),
        sa.Column("agency_contact_description", sa.Text(), nullable=True),
        sa.Column("agency_email_address", sa.Text(), nullable=True),
        sa.Column("agency_email_address_description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["grantor.announcement.announcement_id"],
            name=op.f("announcement_summary_announcement_id_announcement_fkey"),
        ),
        sa.PrimaryKeyConstraint("announcement_summary_id", name=op.f("announcement_summary_pkey")),
        sa.UniqueConstraint(
            "is_forecast", "announcement_id", name=op.f("announcement_summary_is_forecast_uniq")
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("announcement_summary_announcement_id_idx"),
        "announcement_summary",
        ["announcement_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "application_package",
        sa.Column("application_package_id", sa.UUID(), nullable=False),
        sa.Column("announcement_id", sa.UUID(), nullable=False),
        sa.Column("public_application_package_id", sa.Text(), nullable=True),
        sa.Column("application_package_title", sa.Text(), nullable=True),
        sa.Column("opening_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("closing_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("grace_period", sa.BigInteger(), nullable=True),
        sa.Column("contact_info", sa.Text(), nullable=True),
        sa.Column("form_family_id", sa.Integer(), nullable=True),
        sa.Column("announcement_assistance_listing_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_assistance_listing_id"],
            ["grantor.announcement_assistance_listing.announcement_assistance_listing_id"],
            name=op.f(
                "application_package_announcement_assistance_listing_id_announcement_assistance_listing_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["grantor.announcement.announcement_id"],
            name=op.f("application_package_announcement_id_announcement_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["form_family_id"],
            ["grantor.lk_form_family.form_family_id"],
            name=op.f("application_package_form_family_id_lk_form_family_fkey"),
        ),
        sa.PrimaryKeyConstraint("application_package_id", name=op.f("application_package_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("application_package_announcement_id_idx"),
        "application_package",
        ["announcement_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("application_package_form_family_id_idx"),
        "application_package",
        ["form_family_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "link_announcement_summary_applicant_type",
        sa.Column("announcement_summary_id", sa.UUID(), nullable=False),
        sa.Column("applicant_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_summary_id"],
            ["grantor.announcement_summary.announcement_summary_id"],
            name=op.f(
                "link_announcement_summary_applicant_type_announcement_summary_id_announcement_summary_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["applicant_type_id"],
            ["grantor.lk_applicant_type.applicant_type_id"],
            name=op.f(
                "link_announcement_summary_applicant_type_applicant_type_id_lk_applicant_type_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "announcement_summary_id",
            "applicant_type_id",
            name=op.f("link_announcement_summary_applicant_type_pkey"),
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("link_announcement_summary_applicant_type_announcement_summary_id_idx"),
        "link_announcement_summary_applicant_type",
        ["announcement_summary_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("link_announcement_summary_applicant_type_applicant_type_id_idx"),
        "link_announcement_summary_applicant_type",
        ["applicant_type_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "link_announcement_summary_funding_category",
        sa.Column("announcement_summary_id", sa.UUID(), nullable=False),
        sa.Column("funding_category_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_summary_id"],
            ["grantor.announcement_summary.announcement_summary_id"],
            name=op.f(
                "link_announcement_summary_funding_category_announcement_summary_id_announcement_summary_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["funding_category_id"],
            ["grantor.lk_funding_category.funding_category_id"],
            name=op.f(
                "link_announcement_summary_funding_category_funding_category_id_lk_funding_category_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "announcement_summary_id",
            "funding_category_id",
            name=op.f("link_announcement_summary_funding_category_pkey"),
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("link_announcement_summary_funding_category_announcement_summary_id_idx"),
        "link_announcement_summary_funding_category",
        ["announcement_summary_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("link_announcement_summary_funding_category_funding_category_id_idx"),
        "link_announcement_summary_funding_category",
        ["funding_category_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "link_announcement_summary_funding_instrument",
        sa.Column("announcement_summary_id", sa.UUID(), nullable=False),
        sa.Column("funding_instrument_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_summary_id"],
            ["grantor.announcement_summary.announcement_summary_id"],
            name=op.f(
                "link_announcement_summary_funding_instrument_announcement_summary_id_announcement_summary_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["funding_instrument_id"],
            ["grantor.lk_funding_instrument.funding_instrument_id"],
            name=op.f(
                "link_announcement_summary_funding_instrument_funding_instrument_id_lk_funding_instrument_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "announcement_summary_id",
            "funding_instrument_id",
            name=op.f("link_announcement_summary_funding_instrument_pkey"),
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("link_announcement_summary_funding_instrument_announcement_summary_id_idx"),
        "link_announcement_summary_funding_instrument",
        ["announcement_summary_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("link_announcement_summary_funding_instrument_funding_instrument_id_idx"),
        "link_announcement_summary_funding_instrument",
        ["funding_instrument_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "application_package_form",
        sa.Column("application_package_form_id", sa.UUID(), nullable=False),
        sa.Column("application_package_id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_package_id"],
            ["grantor.application_package.application_package_id"],
            name=op.f("application_package_form_application_package_id_application_package_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "application_package_form_id", name=op.f("application_package_form_pkey")
        ),
        sa.UniqueConstraint(
            "application_package_id",
            "form_id",
            name=op.f("application_package_form_application_package_id_uniq"),
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("application_package_form_application_package_id_idx"),
        "application_package_form",
        ["application_package_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "link_application_package_open_to_applicant",
        sa.Column("application_package_id", sa.UUID(), nullable=False),
        sa.Column("application_package_open_to_applicant_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_package_id"],
            ["grantor.application_package.application_package_id"],
            name=op.f(
                "link_application_package_open_to_applicant_application_package_id_application_package_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["application_package_open_to_applicant_id"],
            [
                "grantor.lk_application_package_open_to_applicant.application_package_open_to_applicant_id"
            ],
            name=op.f(
                "link_application_package_open_to_applicant_application_package_open_to_applicant_id_lk_application_package_open_to_applicant_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "application_package_id",
            "application_package_open_to_applicant_id",
            name=op.f("link_application_package_open_to_applicant_pkey"),
        ),
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("link_application_package_open_to_applicant", schema="grantor")
    op.drop_index(
        op.f("application_package_form_application_package_id_idx"),
        table_name="application_package_form",
        schema="grantor",
    )
    op.drop_table("application_package_form", schema="grantor")
    op.drop_index(
        op.f("link_announcement_summary_funding_instrument_funding_instrument_id_idx"),
        table_name="link_announcement_summary_funding_instrument",
        schema="grantor",
    )
    op.drop_index(
        op.f("link_announcement_summary_funding_instrument_announcement_summary_id_idx"),
        table_name="link_announcement_summary_funding_instrument",
        schema="grantor",
    )
    op.drop_table("link_announcement_summary_funding_instrument", schema="grantor")
    op.drop_index(
        op.f("link_announcement_summary_funding_category_funding_category_id_idx"),
        table_name="link_announcement_summary_funding_category",
        schema="grantor",
    )
    op.drop_index(
        op.f("link_announcement_summary_funding_category_announcement_summary_id_idx"),
        table_name="link_announcement_summary_funding_category",
        schema="grantor",
    )
    op.drop_table("link_announcement_summary_funding_category", schema="grantor")
    op.drop_index(
        op.f("link_announcement_summary_applicant_type_applicant_type_id_idx"),
        table_name="link_announcement_summary_applicant_type",
        schema="grantor",
    )
    op.drop_index(
        op.f("link_announcement_summary_applicant_type_announcement_summary_id_idx"),
        table_name="link_announcement_summary_applicant_type",
        schema="grantor",
    )
    op.drop_table("link_announcement_summary_applicant_type", schema="grantor")
    op.drop_index(
        op.f("application_package_form_family_id_idx"),
        table_name="application_package",
        schema="grantor",
    )
    op.drop_index(
        op.f("application_package_announcement_id_idx"),
        table_name="application_package",
        schema="grantor",
    )
    op.drop_table("application_package", schema="grantor")
    op.drop_index(
        op.f("announcement_summary_announcement_id_idx"),
        table_name="announcement_summary",
        schema="grantor",
    )
    op.drop_table("announcement_summary", schema="grantor")
    op.drop_index(
        op.f("announcement_assistance_listing_assistance_listing_id_idx"),
        table_name="announcement_assistance_listing",
        schema="grantor",
    )
    op.drop_index(
        op.f("announcement_assistance_listing_announcement_id_idx"),
        table_name="announcement_assistance_listing",
        schema="grantor",
    )
    op.drop_table("announcement_assistance_listing", schema="grantor")
    op.drop_index(
        op.f("announcement_announcement_category_id_idx"),
        table_name="announcement",
        schema="grantor",
    )
    op.drop_table("announcement", schema="grantor")
    op.drop_table("lk_funding_instrument", schema="grantor")
    op.drop_table("lk_funding_category", schema="grantor")
    op.drop_table("lk_form_family", schema="grantor")
    op.drop_table("lk_application_package_open_to_applicant", schema="grantor")
    op.drop_table("lk_applicant_type", schema="grantor")
    op.drop_table("lk_announcement_category", schema="grantor")
    op.drop_table("lk_announcement_audit_event", schema="grantor")
    # ### end Alembic commands ###
