"""Announcement Summary timestamp change

Revision ID: 63a98454a164
Revises: 4b7e2c9d1a63
Create Date: 2026-10-08 15:16:28.940713

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "63a98454a164"
down_revision = "4b7e2c9d1a63"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "announcement_summary",
        "post_timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "announcement_summary",
        "post_timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        schema="grantor",
    )
    # ### end Alembic commands ###
