"""add opportunity summary tables

Revision ID: 5befb71edfc8
Revises: 97ec15d7034c
Create Date: 2026-09-06 18:34:30.403768

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5befb71edfc8"
down_revision = "97ec15d7034c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunity_summary",
        sa.Column("opportunity_summary_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("summary_description", sa.Text(), nullable=False),
        sa.Column("is_cost_sharing", sa.Boolean(), nullable=False),
        sa.Column("is_forecast", sa.Boolean(), nullable=False),
        sa.Column("post_timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("close_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("close_timestamp_description", sa.Text(), nullable=True),
        sa.Column("archive_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("expected_number_of_awards", sa.BigInteger(), nullable=True),
        sa.Column("estimated_total_program_funding", sa.BigInteger(), nullable=True),
        sa.Column("award_floor", sa.BigInteger(), nullable=True),
        sa.Column("award_ceiling", sa.BigInteger(), nullable=True),
        sa.Column("additional_info_url", sa.Text(), nullable=True),
        sa.Column("additional_info_url_description", sa.Text(), nullable=True),
        sa.Column("forecasted_post_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("forecasted_close_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("forecasted_close_timestamp_description", sa.Text(), nullable=True),
        sa.Column("forecasted_award_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("forecasted_project_start_timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("funding_category_description", sa.Text(), nullable=True),
        sa.Column("applicant_eligibility_description", sa.Text(), nullable=True),
        sa.Column("agency_contact_description", sa.Text(), nullable=True),
        sa.Column("agency_email_address", sa.Text(), nullable=True),
        sa.Column("agency_email_address_description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["grantor.opportunity.opportunity_id"],
            name=op.f("opportunity_summary_opportunity_id_opportunity_fkey"),
        ),
        sa.PrimaryKeyConstraint("opportunity_summary_id", name=op.f("opportunity_summary_pkey")),
        sa.UniqueConstraint(
            "is_forecast", "opportunity_id", name=op.f("opportunity_summary_is_forecast_uniq")
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("opportunity_summary_opportunity_id_idx"),
        "opportunity_summary",
        ["opportunity_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "link_opportunity_summary_applicant_type",
        sa.Column("opportunity_summary_id", sa.UUID(), nullable=False),
        sa.Column("applicant_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["applicant_type_id"],
            ["grantor.lk_applicant_type.applicant_type_id"],
            name=op.f(
                "link_opportunity_summary_applicant_type_applicant_type_id_lk_applicant_type_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_summary_id"],
            ["grantor.opportunity_summary.opportunity_summary_id"],
            name=op.f(
                "link_opportunity_summary_applicant_type_opportunity_summary_id_opportunity_summary_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "opportunity_summary_id",
            "applicant_type_id",
            name=op.f("link_opportunity_summary_applicant_type_pkey"),
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("link_opportunity_summary_applicant_type_applicant_type_id_idx"),
        "link_opportunity_summary_applicant_type",
        ["applicant_type_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("link_opportunity_summary_applicant_type_opportunity_summary_id_idx"),
        "link_opportunity_summary_applicant_type",
        ["opportunity_summary_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "link_opportunity_summary_funding_category",
        sa.Column("opportunity_summary_id", sa.UUID(), nullable=False),
        sa.Column("funding_category_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["funding_category_id"],
            ["grantor.lk_funding_category.funding_category_id"],
            name=op.f(
                "link_opportunity_summary_funding_category_funding_category_id_lk_funding_category_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_summary_id"],
            ["grantor.opportunity_summary.opportunity_summary_id"],
            name=op.f(
                "link_opportunity_summary_funding_category_opportunity_summary_id_opportunity_summary_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "opportunity_summary_id",
            "funding_category_id",
            name=op.f("link_opportunity_summary_funding_category_pkey"),
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("link_opportunity_summary_funding_category_funding_category_id_idx"),
        "link_opportunity_summary_funding_category",
        ["funding_category_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("link_opportunity_summary_funding_category_opportunity_summary_id_idx"),
        "link_opportunity_summary_funding_category",
        ["opportunity_summary_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "link_opportunity_summary_funding_instrument",
        sa.Column("opportunity_summary_id", sa.UUID(), nullable=False),
        sa.Column("funding_instrument_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["funding_instrument_id"],
            ["grantor.lk_funding_instrument.funding_instrument_id"],
            name=op.f(
                "link_opportunity_summary_funding_instrument_funding_instrument_id_lk_funding_instrument_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_summary_id"],
            ["grantor.opportunity_summary.opportunity_summary_id"],
            name=op.f(
                "link_opportunity_summary_funding_instrument_opportunity_summary_id_opportunity_summary_fkey"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "opportunity_summary_id",
            "funding_instrument_id",
            name=op.f("link_opportunity_summary_funding_instrument_pkey"),
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("link_opportunity_summary_funding_instrument_funding_instrument_id_idx"),
        "link_opportunity_summary_funding_instrument",
        ["funding_instrument_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("link_opportunity_summary_funding_instrument_opportunity_summary_id_idx"),
        "link_opportunity_summary_funding_instrument",
        ["opportunity_summary_id"],
        unique=False,
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("link_opportunity_summary_funding_instrument_opportunity_summary_id_idx"),
        table_name="link_opportunity_summary_funding_instrument",
        schema="grantor",
    )
    op.drop_index(
        op.f("link_opportunity_summary_funding_instrument_funding_instrument_id_idx"),
        table_name="link_opportunity_summary_funding_instrument",
        schema="grantor",
    )
    op.drop_table("link_opportunity_summary_funding_instrument", schema="grantor")
    op.drop_index(
        op.f("link_opportunity_summary_funding_category_opportunity_summary_id_idx"),
        table_name="link_opportunity_summary_funding_category",
        schema="grantor",
    )
    op.drop_index(
        op.f("link_opportunity_summary_funding_category_funding_category_id_idx"),
        table_name="link_opportunity_summary_funding_category",
        schema="grantor",
    )
    op.drop_table("link_opportunity_summary_funding_category", schema="grantor")
    op.drop_index(
        op.f("link_opportunity_summary_applicant_type_opportunity_summary_id_idx"),
        table_name="link_opportunity_summary_applicant_type",
        schema="grantor",
    )
    op.drop_index(
        op.f("link_opportunity_summary_applicant_type_applicant_type_id_idx"),
        table_name="link_opportunity_summary_applicant_type",
        schema="grantor",
    )
    op.drop_table("link_opportunity_summary_applicant_type", schema="grantor")
    op.drop_index(
        op.f("opportunity_summary_opportunity_id_idx"),
        table_name="opportunity_summary",
        schema="grantor",
    )
    op.drop_table("opportunity_summary", schema="grantor")
    # ### end Alembic commands ###
