"""add workflow tables

Revision ID: b91e35008f59
Revises: a629d287817e
Create Date: 2026-08-10 13:54:20.800791

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b91e35008f59"
down_revision = "a629d287817e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_mgmt_approval_response_type",
        sa.Column("mgmt_approval_response_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_approval_response_type_id", name=op.f("lk_mgmt_approval_response_type_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "lk_mgmt_approval_type",
        sa.Column("mgmt_approval_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_approval_type_id", name=op.f("lk_mgmt_approval_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "lk_mgmt_workflow_type",
        sa.Column("mgmt_workflow_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("mgmt_workflow_type_id", name=op.f("lk_mgmt_workflow_type_pkey")),
        schema="grantor",
    )
    op.create_table(
        "mgmt_workflow",
        sa.Column("mgmt_workflow_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_workflow_type_id", sa.Integer(), nullable=False),
        sa.Column("mgmt_resource_id", sa.UUID(), nullable=False),
        sa.Column("current_workflow_state", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_resource_id"],
            ["grantor.mgmt_resource.mgmt_resource_id"],
            name=op.f("mgmt_workflow_mgmt_resource_id_mgmt_resource_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_workflow_type_id"],
            ["grantor.lk_mgmt_workflow_type.mgmt_workflow_type_id"],
            name=op.f("mgmt_workflow_mgmt_workflow_type_id_lk_mgmt_workflow_type_fkey"),
        ),
        sa.PrimaryKeyConstraint("mgmt_workflow_id", name=op.f("mgmt_workflow_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_workflow_mgmt_resource_id_idx"),
        "mgmt_workflow",
        ["mgmt_resource_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "mgmt_workflow_event_history",
        sa.Column("mgmt_workflow_event_history_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_workflow_id", sa.UUID(), nullable=True),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sent_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("is_successfully_processed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_workflow_id"],
            ["grantor.mgmt_workflow.mgmt_workflow_id"],
            name=op.f("mgmt_workflow_event_history_mgmt_workflow_id_mgmt_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_workflow_event_history_id", name=op.f("mgmt_workflow_event_history_pkey")
        ),
        schema="grantor",
    )
    op.create_table(
        "mgmt_workflow_approval",
        sa.Column("mgmt_workflow_approval_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_workflow_id", sa.UUID(), nullable=False),
        sa.Column("approving_mgmt_user_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_approval_type_id", sa.Integer(), nullable=False),
        sa.Column("mgmt_workflow_event_history_id", sa.UUID(), nullable=False),
        sa.Column("is_still_valid", sa.Boolean(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("mgmt_approval_response_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approving_mgmt_user_id"],
            ["grantor.mgmt_user.mgmt_user_id"],
            name=op.f("mgmt_workflow_approval_approving_mgmt_user_id_mgmt_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_approval_response_type_id"],
            ["grantor.lk_mgmt_approval_response_type.mgmt_approval_response_type_id"],
            name=op.f(
                "mgmt_workflow_approval_mgmt_approval_response_type_id_lk_mgmt_approval_response_type_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_approval_type_id"],
            ["grantor.lk_mgmt_approval_type.mgmt_approval_type_id"],
            name=op.f("mgmt_workflow_approval_mgmt_approval_type_id_lk_mgmt_approval_type_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_workflow_event_history_id"],
            ["grantor.mgmt_workflow_event_history.mgmt_workflow_event_history_id"],
            name=op.f(
                "mgmt_workflow_approval_mgmt_workflow_event_history_id_mgmt_workflow_event_history_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_workflow_id"],
            ["grantor.mgmt_workflow.mgmt_workflow_id"],
            name=op.f("mgmt_workflow_approval_mgmt_workflow_id_mgmt_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "mgmt_workflow_approval_id", name=op.f("mgmt_workflow_approval_pkey")
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_workflow_approval_mgmt_approval_response_type_id_idx"),
        "mgmt_workflow_approval",
        ["mgmt_approval_response_type_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("mgmt_workflow_approval_mgmt_approval_type_id_idx"),
        "mgmt_workflow_approval",
        ["mgmt_approval_type_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "mgmt_workflow_audit",
        sa.Column("mgmt_workflow_audit_id", sa.UUID(), nullable=False),
        sa.Column("mgmt_workflow_id", sa.UUID(), nullable=False),
        sa.Column("acting_mgmt_user_id", sa.UUID(), nullable=False),
        sa.Column("transition_event", sa.Text(), nullable=False),
        sa.Column("source_state", sa.Text(), nullable=False),
        sa.Column("target_state", sa.Text(), nullable=False),
        sa.Column("mgmt_workflow_event_history_id", sa.UUID(), nullable=False),
        sa.Column("audit_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["acting_mgmt_user_id"],
            ["grantor.mgmt_user.mgmt_user_id"],
            name=op.f("mgmt_workflow_audit_acting_mgmt_user_id_mgmt_user_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_workflow_event_history_id"],
            ["grantor.mgmt_workflow_event_history.mgmt_workflow_event_history_id"],
            name=op.f(
                "mgmt_workflow_audit_mgmt_workflow_event_history_id_mgmt_workflow_event_history_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["mgmt_workflow_id"],
            ["grantor.mgmt_workflow.mgmt_workflow_id"],
            name=op.f("mgmt_workflow_audit_mgmt_workflow_id_mgmt_workflow_fkey"),
        ),
        sa.PrimaryKeyConstraint("mgmt_workflow_audit_id", name=op.f("mgmt_workflow_audit_pkey")),
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mgmt_workflow_audit", schema="grantor")
    op.drop_index(
        op.f("mgmt_workflow_approval_mgmt_approval_type_id_idx"),
        table_name="mgmt_workflow_approval",
        schema="grantor",
    )
    op.drop_index(
        op.f("mgmt_workflow_approval_mgmt_approval_response_type_id_idx"),
        table_name="mgmt_workflow_approval",
        schema="grantor",
    )
    op.drop_table("mgmt_workflow_approval", schema="grantor")
    op.drop_table("mgmt_workflow_event_history", schema="grantor")
    op.drop_index(
        op.f("mgmt_workflow_mgmt_resource_id_idx"), table_name="mgmt_workflow", schema="grantor"
    )
    op.drop_table("mgmt_workflow", schema="grantor")
    op.drop_table("lk_mgmt_workflow_type", schema="grantor")
    op.drop_table("lk_mgmt_approval_type", schema="grantor")
    op.drop_table("lk_mgmt_approval_response_type", schema="grantor")
    # ### end Alembic commands ###
