"""add opportunity audit files

Revision ID: de1486fe72fb
Revises: f70d3358d13d
Create Date: 2026-09-06 19:52:21.206580

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de1486fe72fb"
down_revision = "f70d3358d13d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunity_group_audit",
        sa.Column("opportunity_group_audit_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_group_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_audit_event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column("opportunity_summary_id", sa.UUID(), nullable=True),
        sa.Column("competition_id", sa.UUID(), nullable=True),
        sa.Column("audit_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["grantor.competition.competition_id"],
            name=op.f("opportunity_group_audit_competition_id_competition_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_audit_event_id"],
            ["grantor.lk_opportunity_audit_event.opportunity_audit_event_id"],
            name=op.f(
                "opportunity_group_audit_opportunity_audit_event_id_lk_opportunity_audit_event_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_group_id"],
            ["grantor.opportunity_group.opportunity_group_id"],
            name=op.f("opportunity_group_audit_opportunity_group_id_opportunity_group_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["grantor.opportunity.opportunity_id"],
            name=op.f("opportunity_group_audit_opportunity_id_opportunity_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_summary_id"],
            ["grantor.opportunity_summary.opportunity_summary_id"],
            name=op.f("opportunity_group_audit_opportunity_summary_id_opportunity_summary_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["grantor.user.user_id"],
            name=op.f("opportunity_group_audit_user_id_user_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "opportunity_group_audit_id", name=op.f("opportunity_group_audit_pkey")
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("opportunity_group_audit_opportunity_audit_event_id_idx"),
        "opportunity_group_audit",
        ["opportunity_audit_event_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("opportunity_group_audit_opportunity_group_id_idx"),
        "opportunity_group_audit",
        ["opportunity_group_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("opportunity_group_audit_user_id_idx"),
        "opportunity_group_audit",
        ["user_id"],
        unique=False,
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("opportunity_group_audit_user_id_idx"),
        table_name="opportunity_group_audit",
        schema="grantor",
    )
    op.drop_index(
        op.f("opportunity_group_audit_opportunity_group_id_idx"),
        table_name="opportunity_group_audit",
        schema="grantor",
    )
    op.drop_index(
        op.f("opportunity_group_audit_opportunity_audit_event_id_idx"),
        table_name="opportunity_group_audit",
        schema="grantor",
    )
    op.drop_table("opportunity_group_audit", schema="grantor")
    # ### end Alembic commands ###
