"""Add pending file upload

Revision ID: 639af5afa849
Revises: de1486fe72fb
Create Date: 2026-09-07 00:02:14.255372

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "639af5afa849"
down_revision = "de1486fe72fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_file_scan_status",
        sa.Column("file_scan_status_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("file_scan_status_id", name=op.f("lk_file_scan_status_pkey")),
        schema="grantor",
    )
    op.create_table(
        "pending_file",
        sa.Column("pending_file_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_location", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("file_scan_status_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_scan_status_id"],
            ["grantor.lk_file_scan_status.file_scan_status_id"],
            name=op.f("pending_file_file_scan_status_id_lk_file_scan_status_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["grantor.user.user_id"], name=op.f("pending_file_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("pending_file_id", name=op.f("pending_file_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("pending_file_user_id_idx"),
        "pending_file",
        ["user_id"],
        unique=False,
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("pending_file_user_id_idx"), table_name="pending_file", schema="grantor")
    op.drop_table("pending_file", schema="grantor")
    op.drop_table("lk_file_scan_status", schema="grantor")
    # ### end Alembic commands ###
