"""allow_nullable_post_timestamp

Revision ID: c54a0c5e3c16
Revises: 058f456bcef7
Create Date: 2026-10-05 18:12:15.976480

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c54a0c5e3c16"
down_revision = "058f456bcef7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "announcement_summary",
        "post_timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "announcement_summary",
        "post_timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        schema="grantor",
    )
    # ### end Alembic commands ###
