"""add grantor org path

Revision ID: 438ae6a69f76
Revises: 74587e523544
Create Date: 2026-08-31 12:49:02.418657

"""

import sqlalchemy as sa
from alembic import op

from src.adapters.db.ltree_column import LtreeType

# revision identifiers, used by Alembic.
revision = "438ae6a69f76"
down_revision = "74587e523544"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grantor_organization",
        sa.Column("path", LtreeType(), nullable=False),
        schema="grantor",
    )
    op.create_index(
        "grantor_organization_path_idx",
        "grantor_organization",
        ["path"],
        unique=False,
        schema="grantor",
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "grantor_organization_path_idx",
        table_name="grantor_organization",
        schema="grantor",
        postgresql_using="gist",
    )
    op.drop_column("grantor_organization", "path", schema="grantor")
    # ### end Alembic commands ###
