"""add file tables and audit

Revision ID: 48d36e0698ce
Revises: 713252ec479c
Create Date: 2026-09-15 15:42:30.733608

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "48d36e0698ce"
down_revision = "713252ec479c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_attachment",
        sa.Column("file_attachment_id", sa.UUID(), nullable=False),
        sa.Column("file_location", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("file_description", sa.Text(), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("file_attachment_id", name=op.f("file_attachment_pkey")),
        schema="grantor",
    )
    op.create_table(
        "announcement_attachment",
        sa.Column("announcement_attachment_id", sa.UUID(), nullable=False),
        sa.Column("announcement_id", sa.UUID(), nullable=False),
        sa.Column("file_attachment_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["grantor.announcement.announcement_id"],
            name=op.f("announcement_attachment_announcement_id_announcement_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["file_attachment_id"],
            ["grantor.file_attachment.file_attachment_id"],
            name=op.f("announcement_attachment_file_attachment_id_file_attachment_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "announcement_attachment_id", name=op.f("announcement_attachment_pkey")
        ),
        sa.UniqueConstraint(
            "announcement_id",
            "file_attachment_id",
            name=op.f("announcement_attachment_announcement_id_uniq"),
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("announcement_attachment_announcement_id_idx"),
        "announcement_attachment",
        ["announcement_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("announcement_attachment_file_attachment_id_idx"),
        "announcement_attachment",
        ["file_attachment_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "application_package_instruction",
        sa.Column("application_package_instruction_id", sa.UUID(), nullable=False),
        sa.Column("application_package_id", sa.UUID(), nullable=False),
        sa.Column("file_attachment_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_package_id"],
            ["grantor.application_package.application_package_id"],
            name=op.f(
                "application_package_instruction_application_package_id_application_package_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["file_attachment_id"],
            ["grantor.file_attachment.file_attachment_id"],
            name=op.f("application_package_instruction_file_attachment_id_file_attachment_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "application_package_instruction_id", name=op.f("application_package_instruction_pkey")
        ),
        sa.UniqueConstraint(
            "application_package_id",
            "file_attachment_id",
            name=op.f("application_package_instruction_application_package_id_uniq"),
        ),
        schema="grantor",
    )
    op.create_index(
        op.f("application_package_instruction_application_package_id_idx"),
        "application_package_instruction",
        ["application_package_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("application_package_instruction_file_attachment_id_idx"),
        "application_package_instruction",
        ["file_attachment_id"],
        unique=False,
        schema="grantor",
    )
    op.create_table(
        "announcement_audit",
        sa.Column("announcement_audit_id", sa.UUID(), nullable=False),
        sa.Column("announcement_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("announcement_audit_event_id", sa.Integer(), nullable=False),
        sa.Column("announcement_summary_id", sa.UUID(), nullable=True),
        sa.Column("announcement_attachment_id", sa.UUID(), nullable=True),
        sa.Column("application_package_id", sa.UUID(), nullable=True),
        sa.Column("application_package_instruction_id", sa.UUID(), nullable=True),
        sa.Column("audit_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_attachment_id"],
            ["grantor.announcement_attachment.announcement_attachment_id"],
            name=op.f("announcement_audit_announcement_attachment_id_announcement_attachment_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["announcement_audit_event_id"],
            ["grantor.lk_announcement_audit_event.announcement_audit_event_id"],
            name=op.f(
                "announcement_audit_announcement_audit_event_id_lk_announcement_audit_event_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["grantor.announcement.announcement_id"],
            name=op.f("announcement_audit_announcement_id_announcement_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["announcement_summary_id"],
            ["grantor.announcement_summary.announcement_summary_id"],
            name=op.f("announcement_audit_announcement_summary_id_announcement_summary_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["application_package_id"],
            ["grantor.application_package.application_package_id"],
            name=op.f("announcement_audit_application_package_id_application_package_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["application_package_instruction_id"],
            ["grantor.application_package_instruction.application_package_instruction_id"],
            name=op.f(
                "announcement_audit_application_package_instruction_id_application_package_instruction_fkey"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["grantor.user.user_id"], name=op.f("announcement_audit_user_id_user_fkey")
        ),
        sa.PrimaryKeyConstraint("announcement_audit_id", name=op.f("announcement_audit_pkey")),
        schema="grantor",
    )
    op.create_index(
        op.f("announcement_audit_announcement_audit_event_id_idx"),
        "announcement_audit",
        ["announcement_audit_event_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("announcement_audit_announcement_id_idx"),
        "announcement_audit",
        ["announcement_id"],
        unique=False,
        schema="grantor",
    )
    op.create_index(
        op.f("announcement_audit_user_id_idx"),
        "announcement_audit",
        ["user_id"],
        unique=False,
        schema="grantor",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("announcement_audit_user_id_idx"), table_name="announcement_audit", schema="grantor"
    )
    op.drop_index(
        op.f("announcement_audit_announcement_id_idx"),
        table_name="announcement_audit",
        schema="grantor",
    )
    op.drop_index(
        op.f("announcement_audit_announcement_audit_event_id_idx"),
        table_name="announcement_audit",
        schema="grantor",
    )
    op.drop_table("announcement_audit", schema="grantor")
    op.drop_index(
        op.f("application_package_instruction_file_attachment_id_idx"),
        table_name="application_package_instruction",
        schema="grantor",
    )
    op.drop_index(
        op.f("application_package_instruction_application_package_id_idx"),
        table_name="application_package_instruction",
        schema="grantor",
    )
    op.drop_table("application_package_instruction", schema="grantor")
    op.drop_index(
        op.f("announcement_attachment_file_attachment_id_idx"),
        table_name="announcement_attachment",
        schema="grantor",
    )
    op.drop_index(
        op.f("announcement_attachment_announcement_id_idx"),
        table_name="announcement_attachment",
        schema="grantor",
    )
    op.drop_table("announcement_attachment", schema="grantor")
    op.drop_table("file_attachment", schema="grantor")
    # ### end Alembic commands ###
