name: Deploy frontend
run-name: Deploy ${{ inputs.version || 'main' }} to Frontend ${{ inputs.environment || 'dev' }}

on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
      - "infra/frontend/**"
      - "infra/modules/**"
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
      version:
        required: true
        default: "main"
        description: Tag or branch or SHA to deploy
      skip_checks:
        type: boolean
        default: false
        description: Skip unit tests, lint, etc
      skip_vuln_scans:
        type: boolean
        default: false
        description: Skip vulnerability scans
  workflow_call:
    inputs:
      environment:
        description: Environment to deploy to
        required: false
        default: "dev"
        type: string
      version:
        required: false
        default: ""
        description: Tag or branch or SHA to deploy
        type: string
      skip_checks:
        type: boolean
        default: false
        description: Skip unit tests, lint, etc while deploying
      skip_vuln_scans:
        type: boolean
        default: false
        description: Skip vulnerability scans while deploying

jobs:
  frontend-checks:
    name: Run Frontend Checks
    uses: ./.github/workflows/ci-frontend.yml
    with:
      skip_checks: ${{ inputs.skip_checks != null && inputs.skip_checks != false }}

  vulnerability-scans:
    name: Vulnerability Scans
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: frontend
      fail_on_vulns: false
      skip_vuln_scans: ${{ inputs.skip_vuln_scans != null && inputs.skip_vuln_scans != false }}

  deploy:
    name: Deploy
    needs: [frontend-checks, vulnerability-scans]
    uses: ./.github/workflows/deploy.yml
    with:
      app_name: "frontend"
      environment: ${{ inputs.environment || 'dev' }}
      version: ${{ inputs.version || github.ref }}

  send-slack-notification:
    if: failure() && (github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/main'))
    needs: [frontend-checks, vulnerability-scans, deploy]
    uses: ./.github/workflows/send-slack-notification.yml
    secrets: inherit
